### ISSUE TITLE
太棒啦已经用上啦

### ISSUE THREAD

**Issue by pengpenging** [inoyna11/jd28#1]
大佬真的牛逼

**Comment by pengpenging** [comment]
但是JD的cookie不到十分钟变化一次 怎么解决啊

**Comment by x1737886903** [comment]
请问是每天自动的吗？还是需要手动修改的

**Comment by pengpenging** [comment]
> 请问是每天自动的吗？还是需要手动修改的

cookie每天都需要修改

**Comment by x1737886903** [comment]
用docker运行可以吗？是否可以不用每天改cookie

**Comment by xlfree** [comment]
怎么运行啊

**Comment by pengpenging** [comment]
> 用docker运行可以吗？是否可以不用每天改cookie

这个我不清楚哦

**Comment by pengpenging** [comment]
> 怎么运行啊

哔哩哔哩有教程的

**Comment by xlfree** [comment]
> > 怎么运行啊
> 
> 哔哩哔哩有教程的

求链接，谢谢
