### ISSUE TITLE
这个错误是怎么回事大佬

### ISSUE THREAD

**Issue by candlezha** [inoyna11/jd28#10]
The job was not started because recent account payments have failed. Please ensure payment in order to proceed.

**Comment by inoyna11** [comment]
> The job was not started because recent account payments have failed. Please ensure payment in order to proceed.

是什么脚本提示的这个

**Comment by lijiaqigz** [comment]
全部都显示这个 jd_zoo  动物联萌

**Comment by candlezha** [comment]
> > The job was not started because recent account payments have failed. Please ensure payment in order to proceed.
> 
> 是什么脚本提示的这个

所有脚本

**Comment by lijiaqigz** [comment]
选公开，不要 选 私人项目， 已解决。

**Comment by inoyna11** [comment]
> > > The job was not started because recent account payments have failed. Please ensure payment in order to proceed.
> > 
> > 
> > 是什么脚本提示的这个
> 
> 所有脚本

按照教程来不会出现这个提示的。
删除仓库，重新导入，别的选项不要点

**Comment by candlezha** [comment]
> > > > The job was not started because recent account payments have failed. Please ensure payment in order to proceed.
> > > 
> > > 
> > > 是什么脚本提示的这个
> > 
> > 
> > 所有脚本
> 
> 按照教程来不会出现这个提示的。
> 删除仓库，重新导入，别的选项不要点

解决了，改成公开就行了
