### ISSUE TITLE
点点券 任务已执行 但是操作失败

### ISSUE THREAD

**Issue by KissCode** [inoyna11/jd28#101]
【点击“领券”】 任务未领取,开始领取此任务
领取任务结果：{"rtn_code":403,"rtn_msg":"非法请求！"}
【点击“领券”】 任务领取成功,开始完成此任务
需等待15秒
点击首页领券图标(进入领券中心浏览15s)任务:{"code":"600","echo":"signature verification failed"}
【浏览精选活动】 任务未领取,开始领取此任务
领取任务结果：{"rtn_code":403,"rtn_msg":"非法请求！"}
【浏览精选活动】 任务领取成功,开始完成此任务
【玩锦鲤红包】 任务未领取,开始领取此任务
领取任务结果：{"rtn_code":403,"rtn_msg":"非法请求！"}
【玩锦鲤红包】 任务领取成功,开始完成此任务
做任务结果：{"data":{"biz_code":1002,"biz_msg":"用户未领取该任务"},"rtn_code":0,"rtn_msg":"请求成功！"}
【玩拼券活动】 任务未领取,开始领取此任务
领取任务结果：{"rtn_code":403,"rtn_msg":"非法请求！"}
【玩拼券活动】 任务领取成功,开始完成此任务
做任务结果：{"data":{"biz_code":1002,"biz_msg":"用户未领取该任务"},"rtn_code":0,"rtn_msg":"请求成功！"}
【逛券后9.9】 任务未领取,开始领取此任务
领取任务结果：{"rtn_code":403,"rtn_msg":"非法请求！"}
【逛券后9.9】 任务领取成功,开始完成此任务
做任务结果：{"data":{"biz_code":1002,"biz_msg":"用户未领取该任务"},"rtn_code":0,"rtn_msg":"请求成功！"}
【去买省钱券包】 任务未领取,开始领取此任务
领取任务结果：{"rtn_code":403,"rtn_msg":"非法请求！"}
【去买省钱券包】 任务领取成功,开始完成此任务
做任务结果：{"data":{"biz_code":1002,"biz_msg":"用户未领取该任务"},"rtn_code":0,"rtn_msg":"请求成功！"}

开始每日签到
每日签到失败：{"rtn_code":403,"rtn_msg":"非法请求！"}

**Comment by inoyna11** [comment]
> 【点击“领券”】 任务未领取,开始领取此任务
> 领取任务结果：{"rtn_code":403,"rtn_msg":"非法请求！"}
> 【点击“领券”】 任务领取成功,开始完成此任务
> 需等待15秒
> 点击首页领券图标(进入领券中心浏览15s)任务:{"code":"600","echo":"signature verification failed"}
> 【浏览精选活动】 任务未领取,开始领取此任务
> 领取任务结果：{"rtn_code":403,"rtn_msg":"非法请求！"}
> 【浏览精选活动】 任务领取成功,开始完成此任务
> 【玩锦鲤红包】 任务未领取,开始领取此任务
> 领取任务结果：{"rtn_code":403,"rtn_msg":"非法请求！"}
> 【玩锦鲤红包】 任务领取成功,开始完成此任务
> 做任务结果：{"data":{"biz_code":1002,"biz_msg":"用户未领取该任务"},"rtn_code":0,"rtn_msg":"请求成功！"}
> 【玩拼券活动】 任务未领取,开始领取此任务
> 领取任务结果：{"rtn_code":403,"rtn_msg":"非法请求！"}
> 【玩拼券活动】 任务领取成功,开始完成此任务
> 做任务结果：{"data":{"biz_code":1002,"biz_msg":"用户未领取该任务"},"rtn_code":0,"rtn_msg":"请求成功！"}
> 【逛券后9.9】 任务未领取,开始领取此任务
> 领取任务结果：{"rtn_code":403,"rtn_msg":"非法请求！"}
> 【逛券后9.9】 任务领取成功,开始完成此任务
> 做任务结果：{"data":{"biz_code":1002,"biz_msg":"用户未领取该任务"},"rtn_code":0,"rtn_msg":"请求成功！"}
> 【去买省钱券包】 任务未领取,开始领取此任务
> 领取任务结果：{"rtn_code":403,"rtn_msg":"非法请求！"}
> 【去买省钱券包】 任务领取成功,开始完成此任务
> 做任务结果：{"data":{"biz_code":1002,"biz_msg":"用户未领取该任务"},"rtn_code":0,"rtn_msg":"请求成功！"}
> 
> 开始每日签到
> 每日签到失败：{"rtn_code":403,"rtn_msg":"非法请求！"}

那是因为京东加验证了，脚本不能用了

**Comment by KissCode** [comment]
收到
