### ISSUE TITLE
是否可以实现内部账户自动互助呢？

### ISSUE THREAD

**Issue by PMYuYu** [inoyna11/jd28#103]

**Comment by inoyna11** [comment]
> _No description provided._

个别脚本可以，比如动物连萌

**Comment by wangzh1004** [comment]
动物连萌后面的怪兽助力好像一直都是火爆的，京东金融的后面好像做不了

**Comment by inoyna11** [comment]
> 动物连萌后面的怪兽助力好像一直都是火爆的，京东金融的后面好像做不了

有内部互助的，互助之后多余的会助力内置互助码
