### ISSUE TITLE
怎样加入618zoo内部互助的list呢

### ISSUE THREAD

**Issue by zhangleqin** [inoyna11/jd28#105]
互助码：ZXTKT0189KUiHklFoBWOfhr0kwFjRWn6-7zx55awQ

PK互助码：sSKNX-MpqKOZvOXmzseMRWHJaAP3-xc43Vannu5WQrVLl259ePHuE72R

后续的PK互助似乎没结束 继续用别的语句在跑

zhangleqin007 去助力PK码 sSKNX-MpqKOJsNu-np2LVqv2xNBizM0RkzUsiED24pNX2x4bnEVEbskw0Slwekdk
已经助力过该队伍
zhangleqin007 去助力PK码 S
怪兽大作战助力失败：{"code":0,"data":{"bizCode":-3001,"bizMsg":"活动太火爆","success":false},"msg":"调用成功"}
zhangleqin007 去助力PK码 e
怪兽大作战助力失败：{"code":0,"data":{"bizCode":-3001,"bizMsg":"活动太火爆","success":false},"msg":"调用成功"}
zhangleqin007 去助力PK码 "
怪兽大作战助力失败：{"code":0,"data":{"bizCode":-3001,"bizMsg":"活动太火爆","success":false},"msg":"调用成功"}
zhangleqin007 去助力PK码 B
怪兽大作战助力失败：{"code":0,"data":{"bizCode":-3001,"bizMsg":"活动太火爆","success":false},"msg":"调用成功"}
zhangleqin007 去助力PK码 P

**Comment by inoyna11** [comment]
> 互助码：ZXTKT0189KUiHklFoBWOfhr0kwFjRWn6-7zx55awQ
> 
> PK互助码：sSKNX-MpqKOZvOXmzseMRWHJaAP3-xc43Vannu5WQrVLl259ePHuE72R
> 
> 后续的PK互助似乎没结束 继续用别的语句在跑
> 
> zhangleqin007 去助力PK码 sSKNX-MpqKOJsNu-np2LVqv2xNBizM0RkzUsiED24pNX2x4bnEVEbskw0Slwekdk
> 已经助力过该队伍
> zhangleqin007 去助力PK码 S
> 怪兽大作战助力失败：{"code":0,"data":{"bizCode":-3001,"bizMsg":"活动太火爆","success":false},"msg":"调用成功"}
> zhangleqin007 去助力PK码 e
> 怪兽大作战助力失败：{"code":0,"data":{"bizCode":-3001,"bizMsg":"活动太火爆","success":false},"msg":"调用成功"}
> zhangleqin007 去助力PK码 "
> 怪兽大作战助力失败：{"code":0,"data":{"bizCode":-3001,"bizMsg":"活动太火爆","success":false},"msg":"调用成功"}
> zhangleqin007 去助力PK码 B
> 怪兽大作战助力失败：{"code":0,"data":{"bizCode":-3001,"bizMsg":"活动太火爆","success":false},"msg":"调用成功"}
> zhangleqin007 去助力PK码 P

这个脚本是优先内部互助的，多余的会助力内置助力码
