### ISSUE TITLE
删除运行日志提示说没有需要删除的

### ISSUE THREAD

**Issue by 1976107361** [inoyna11/jd28#107]

**Comment by inoyna11** [comment]
> _No description provided._

不用管

**Comment by 1976107361** [comment]
搞个交流群呗，有利于大家解决问题

**Comment by inoyna11** [comment]
> 搞个交流群呗，有利于大家解决问题

等过几天，这个库应该快不行了

**Comment by pengpenging** [comment]
> > 搞个交流群呗，有利于大家解决问题
> 
> 等过几天，这个库应该快不行了

好的 大佬
