### ISSUE TITLE
京喜财富岛

### ISSUE THREAD

**Issue by 13071558875** [inoyna11/jd28#111]
京喜财富岛 joinGroup API请求失败，请检查网路重试

**Comment by 13071558875** [comment]
大佬，有些签到失败了，我看了一下是需要验证码能绕过吗

**Comment by inoyna11** [comment]
> 大佬，有些签到失败了，我看了一下是需要验证码，能过吗

财富岛任务完成就行了，报错不用管
至于其他的签到，要验证码的你就每天手动签到一下，几天就好了
