### ISSUE TITLE
今天宠汪汪任务好像失败了，状态读不出？

### ISSUE THREAD

**Issue by aburdchen415** [inoyna11/jd28#113]

**Comment by aburdchen415** [comment]
TypeError: $.getPetTaskConfigRes.datas is not iterable!

**Comment by inoyna11** [comment]
> TypeError: $.getPetTaskConfigRes.datas is not iterable!

好的，等我修复

**Comment by aburdchen415** [comment]
> > TypeError: $.getPetTaskConfigRes.datas is not iterable!
> 
> 好的，等我修复

看见有更新了，但是好像还是不行，加油！！！哈哈

**Comment by aburdchen415** [comment]
宠汪汪还是不行啊。。。
