### ISSUE TITLE
口袋书店入口在哪里哈

### ISSUE THREAD

**Issue by Deskyo** [inoyna11/jd28#114]

**Comment by inoyna11** [comment]
> _No description provided._

首页京东图书那里

**Comment by Deskyo** [comment]
> 
> 
> > _No description provided._
> 
> 首页京东图书那里

脚本里也是这样说的，但是我从京东图书里进去了也没看到。请问你找到了吗？

**Comment by daxinnan** [comment]
> > > _No description provided._
> > 
> > 
> > 首页京东图书那里
> 
> 脚本里也是这样说的，但是我从京东图书里进去了也没看到。请问你找到了吗？

往下拉不是有个每日参与活动 赢京豆 抽大奖吗 就它

**Comment by Deskyo** [comment]
> 
> 
> > > > _No description provided._
> > > 
> > > 
> > > 首页京东图书那里
> > 
> > 
> > 脚本里也是这样说的，但是我从京东图书里进去了也没看到。请问你找到了吗？
> 
> 往下拉不是有个每日参与活动 赢京豆 抽大奖吗 就它

哦哦好的！ 谢谢啦！
