### ISSUE TITLE
翻翻乐入口在哪里呀

### ISSUE THREAD

**Issue by xdeancc** [inoyna11/jd28#117]
一直显示翻翻乐翻倍失败，想去看下是个什么情况

**Comment by inoyna11** [comment]
> 一直显示翻翻乐翻倍失败，想去看下是个什么情况

京东极速版-省钱大赢家

**Comment by xdeancc** [comment]
> > 一直显示翻翻乐翻倍失败，想去看下是个什么情况
> 
> 京东极速版-省钱大赢家

搞定了，谢谢

**Comment by xdeancc** [comment]
> > 一直显示翻翻乐翻倍失败，想去看下是个什么情况
> 
> 京东极速版-省钱大赢家

奇怪，我已经设好了微信绑定，还是显示翻倍失败
