### ISSUE TITLE
翻翻乐翻倍机制

### ISSUE THREAD

**Issue by pengpenging** [inoyna11/jd28#118]
这个翻几倍，翻到多少提现是随机的嘛？

**Comment by inoyna11** [comment]
> 这个翻几倍，翻到多少提现是随机的嘛？

是的

**Comment by pengpenging** [comment]
> > 这个翻几倍，翻到多少提现是随机的嘛？
> 
> 是的

好的，感谢大佬的程序让我抽中试用的粽子嘿嘿，可以赞助下嘛？辛苦啦

**Comment by inoyna11** [comment]
> > > 这个翻几倍，翻到多少提现是随机的嘛？
> > 
> > 
> > 是的
> 
> 好的，感谢大佬的程序让我抽中试用的粽子嘿嘿，可以赞助下嘛？辛苦啦

![mm_reward_qrcode_1622884441853](https://user-images.githubusercontent.com/82111047/120886626-830fc000-c621-11eb-876b-3c85d2a095c1.png)
天气炎热，好久没吃过旺旺碎冰冰了

**Comment by pengpenging** [comment]
> > > > 这个翻几倍，翻到多少提现是随机的嘛？
> > > 
> > > 
> > > 是的
> > 
> > 
> > 好的，感谢大佬的程序让我抽中试用的粽子嘿嘿，可以赞助下嘛？辛苦啦
> 
> ![mm_reward_qrcode_1622884441853](https://user-images.githubusercontent.com/82111047/120886626-830fc000-c621-11eb-876b-3c85d2a095c1.png)
> 天气炎热，好久没吃过旺旺碎冰冰了

一点赞赏不足敬意，待大佬拉我进群嘿嘿~

**Comment by inoyna11** [comment]
> > > > > 这个翻几倍，翻到多少提现是随机的嘛？
> > > > 
> > > > 
> > > > 是的
> > > 
> > > 
> > > 好的，感谢大佬的程序让我抽中试用的粽子嘿嘿，可以赞助下嘛？辛苦啦
> > 
> > 
> > ![mm_reward_qrcode_1622884441853](https://user-images.githubusercontent.com/82111047/120886626-830fc000-c621-11eb-876b-3c85d2a095c1.png)
> > 天气炎热，好久没吃过旺旺碎冰冰了
> 
> 一点赞赏不足敬意，待大佬拉我进群嘿嘿~

群就不用了，管理起来太麻烦
如果这个库没了那我就会在这个库继续更新https://github.com/1483615512
可以先关注
