### ISSUE TITLE
618活动中   自动开通会员的任务   以及     浏览加购5个商品   的任务没有完成

### ISSUE THREAD

**Issue by liujm1024** [inoyna11/jd28#12]

**Comment by inoyna11** [comment]
> _No description provided._

lxk0301后续的脚本默认不做加购和开卡任务

**Comment by Dron1sh** [comment]
那有配置能让执行吗？

**Comment by inoyna11** [comment]
> 那有配置能让执行吗？

暂时没有，因为动物连萌脚本是lxk0301写的半成品，脚本不太完善，等他更新脚本的话我会搬过来，到时候应该就可以了，差不多这一二天
