### ISSUE TITLE
希望移除我仓库内的两个脚本

### ISSUE THREAD

**Issue by hyzaw** [inoyna11/jd28#121]
ddo_pk.js
ddo_joy_reward.js
谢谢

**Comment by inoyna11** [comment]
> ddo_pk.js
> ddo_joy_reward.js
> 谢谢

自己禁用

**Comment by hyzaw** [comment]
> > ddo_pk.js
> > ddo_joy_reward.js
> > 谢谢
> 
> 自己禁用

你好 我是这两个脚本的作者 我不允许你将其存放在本仓库

**Comment by inoyna11** [comment]
> > > ddo_pk.js
> > > ddo_joy_reward.js
> > > 谢谢
> > 
> > 
> > 自己禁用
> 
> 你好 我是这两个脚本的作者 我不允许你将其存放在本仓库

删了
