### ISSUE TITLE
邀请好友助力的任务能自动完成吗？

### ISSUE THREAD

**Issue by Dron1sh** [inoyna11/jd28#13]

**Comment by inoyna11** [comment]
> _No description provided._

具体哪个脚本

**Comment by Dron1sh** [comment]
> > _No description provided._
> 
> 具体哪个脚本

热爱狂欢趴

**Comment by inoyna11** [comment]
> > > _No description provided._
> > 
> > 
> > 具体哪个脚本
> 
> 热爱狂欢趴

已经更新账号内部互助，手动同步下脚本

**Comment by Dron1sh** [comment]
> > > > _No description provided._
> > > 
> > > 
> > > 具体哪个脚本
> > 
> > 
> > 热爱狂欢趴
> 
> 已经更新账号内部互助，手动同步下脚本

每日签到里的金币可以自动收吗？

**Comment by inoyna11** [comment]
> > > > > _No description provided._
> > > > 
> > > > 
> > > > 具体哪个脚本
> > > 
> > > 
> > > 热爱狂欢趴
> > 
> > 
> > 已经更新账号内部互助，手动同步下脚本
> 
> 每日签到里的金币可以自动收吗？

脚本每2小时运行一次，就是收那个金币的
