### ISSUE TITLE
jdPetShareCodes.js 这个有执行吗？对应哪个ACTIONS

### ISSUE THREAD

**Issue by yaj806** [inoyna11/jd28#14]
我i想找萌宠的互助码?

**Comment by inoyna11** [comment]
> 我i想找萌宠的互助码?

东东萌宠互助的话添加PETSHARECODES环境变量，按照lxk0301的环境变量格式填写。
先同步下脚本在添加，因为我刚刚才加上去

**Comment by yaj806** [comment]
![image](https://user-images.githubusercontent.com/62924780/119469430-ed02ac80-bd79-11eb-8926-72ac318d5dc1.png)
请问怎么同步脚本，同步任务都失败了，怎么手动同步，谢谢

**Comment by yaj806** [comment]
> 东东萌宠互助的话添加PETSHARECODES环境变量，按照lxk0301的环境变量格式填写。

请问如何手动同步脚本，自动同步的都失败了，谢谢

**Comment by guanyi1024** [comment]
同问 怎么手动同步

**Comment by guanyi1024** [comment]
> > 我i想找萌宠的互助码?
> 
> 东东萌宠互助的话添加PETSHARECODES环境变量，按照lxk0301的环境变量格式填写。
> 先同步下脚本在添加，因为我刚刚才加上去

同问 怎么手动同步 按照步骤重新再添加一个吗？

**Comment by inoyna11** [comment]
> > > 我i想找萌宠的互助码?
> > 
> > 
> > 东东萌宠互助的话添加PETSHARECODES环境变量，按照lxk0301的环境变量格式填写。
> > 先同步下脚本在添加，因为我刚刚才加上去
> 
> 同问 怎么手动同步 按照步骤重新再添加一个吗？

点击仓库actions，到里面的搜索框里搜同步，等一分钟就自动同步过来了

**Comment by inoyna11** [comment]
> > 东东萌宠互助的话添加PETSHARECODES环境变量，按照lxk0301的环境变量格式填写。
> 
> 请问如何手动同步脚本，自动同步的都失败了，谢谢

环境变量添加PAT了没有

**Comment by inoyna11** [comment]
> ![image](https://user-images.githubusercontent.com/62924780/119469430-ed02ac80-bd79-11eb-8926-72ac318d5dc1.png)
> 请问怎么同步脚本，同步任务都失败了，怎么手动同步，谢谢

不要fork使用，按照我的教程，最后添加PAT就可以自动同步了

**Comment by yaj806** [comment]
> > ![image](https://user-images.githubusercontent.com/62924780/119469430-ed02ac80-bd79-11eb-8926-72ac318d5dc1.png)
> > 请问怎么同步脚本，同步任务都失败了，怎么手动同步，谢谢
> 
> 不要fork使用，按照我的教程，最后添加PAT就可以自动同步了

完全按照你的教程来的，我现在把库删掉，重新搞了一个，PAT肯定是加了的，第一次是成功的，后面失败了，现在重新建了一个是好的，另外提示

![image](https://user-images.githubusercontent.com/62924780/119478876-bda46d80-bd82-11eb-9ef9-79701262f3a7.png)

这个要怎么处理啊

**Comment by inoyna11** [comment]
> > > ![image](https://user-images.githubusercontent.com/62924780/119469430-ed02ac80-bd79-11eb-8926-72ac318d5dc1.png)
> > > 请问怎么同步脚本，同步任务都失败了，怎么手动同步，谢谢
> > 
> > 
> > 不要fork使用，按照我的教程，最后添加PAT就可以自动同步了
> 
> 完全按照你的教程来的，我现在把库删掉，重新搞了一个，PAT肯定是加了的，第一次是成功的，后面失败了，现在重新建了一个是好的，另外提示
> 
> ![image](https://user-images.githubusercontent.com/62924780/119478876-bda46d80-bd82-11eb-9ef9-79701262f3a7.png)
> 
> 这个要怎么处理啊

这个是账号被github限制了，要到6月1号解除，你是不是用ac干什么非法的事情了，一般人使用不可能被限制的。
等不及的话只能重新申请个号来使用了

**Comment by yaj806** [comment]
> 等不及的话只能重新申请个号来使用了

申请的一个新号，啥都没有干，完全按你的教程来的

**Comment by inoyna11** [comment]
> > 等不及的话只能重新申请个号来使用了
> 
> 申请的一个新号，啥都没有干，完全按你的教程来的

我刚刚用别的号复制了下我的仓库，是可以复制的。
应该就是你账号的问题，也有可能是ip被封。
挂个代理然后换个浏览器登陆试试

**Comment by yaj806** [comment]
> 挂个代理然后换个浏览器登陆试试

复制是可以的，用一天就有这个提示了，貌似啥东西快满了

**Comment by inoyna11** [comment]
> > 挂个代理然后换个浏览器登陆试试
> 
> 复制是可以的，用一天就有这个提示了，貌似啥东西快满了

是你最近一直在疯狂的使用actions运行脚本被限制了。
等下个月1号就好了

**Comment by stephenjack2028** [comment]
> > > 挂个代理然后换个浏览器登陆试试
> > 
> > 
> > 复制是可以的，用一天就有这个提示了，貌似啥东西快满了
> 
> 是你最近一直在疯狂的使用actions运行脚本被限制了。
> 等下个月1号就好了

是不是每次点开action都会运行？我就这一个库，其他没东西，是不是定时任务执行的太频繁了？我看有些流程自动执行了好多遍

**Comment by inoyna11** [comment]
> > > > 挂个代理然后换个浏览器登陆试试
> > > 
> > > 
> > > 复制是可以的，用一天就有这个提示了，貌似啥东西快满了
> > 
> > 
> > 是你最近一直在疯狂的使用actions运行脚本被限制了。
> > 等下个月1号就好了
> 
> 是不是每次点开action都会运行？我就这一个库，其他没东西，是不是定时任务执行的太频繁了？我看有些流程自动执行了好多遍

你在导入仓库的时候是不是把仓库设置成私有了？如果是的话改成公开

**Comment by yaj806** [comment]
> > > > > 挂个代理然后换个浏览器登陆试试
> > > > 
> > > > 
> > > > 复制是可以的，用一天就有这个提示了，貌似啥东西快满了
> > > 
> > > 
> > > 是你最近一直在疯狂的使用actions运行脚本被限制了。
> > > 等下个月1号就好了
> > 
> > 
> > 是不是每次点开action都会运行？我就这一个库，其他没东西，是不是定时任务执行的太频繁了？我看有些流程自动执行了好多遍
> 
> 你在导入仓库的时候是不是把仓库设置成私有了？如果是的话改成公开

是的，是设置的私有，多谢🙏
