### ISSUE TITLE
PUSH_PLUS_TOKEN：push+发送一对一通知消息失败：用户信息状态不合法

### ISSUE THREAD

**Issue by lijiaqigz** [inoyna11/jd28#15]
PUSH_PLUS_TOKEN： 配置token后，无法收到推送。
push+发送一对一通知消息失败：用户信息状态不合法

**Comment by inoyna11** [comment]
> PUSH_PLUS_TOKEN： 配置token后，无法收到推送。
> push+发送一对一通知消息失败：用户信息状态不合法

哪个脚本

**Comment by lijiaqigz** [comment]
昨日收益， 目前在这个试了，会有这个问题。

**Comment by inoyna11** [comment]
> 昨日收益， 目前在这个试了，会有这个问题。

这个脚本推送是没有问题了，因为我就是push+推送。
仔细看看是不是环境变量添加错误，如果是一对多推送，PUSH_PLUS_USER是填群组编号，不是填群组昵称。
如果还不行，先自己在push+官网手动发消息看看能不能收到

**Comment by BruceLee569** [comment]
> > 昨日收益， 目前在这个试了，会有这个问题。
> 
> 这个脚本推送是没有问题了，因为我就是push+推送。
> 仔细看看是不是环境变量添加错误，如果是一对多推送，PUSH_PLUS_USER是填群组编号，不是填群组昵称。
> 如果还不行，先自己在push+官网手动发消息看看能不能收到

我也是发送失败，返回“用户信息状态不合法”

排查后发现是 pushplus的地址改了，将代码里 `pushPlusNotify` 的 post url 换成 `http://pushplus.hxtrip.com/send` 就发送成功了。

另外提个建议，这么多脚本为什么每个都单独跑 workflow，合并成一个不好么，太多重复性工作了。。

**Comment by inoyna11** [comment]
> > > 昨日收益， 目前在这个试了，会有这个问题。
> > 
> > 
> > 这个脚本推送是没有问题了，因为我就是push+推送。
> > 仔细看看是不是环境变量添加错误，如果是一对多推送，PUSH_PLUS_USER是填群组编号，不是填群组昵称。
> > 如果还不行，先自己在push+官网手动发消息看看能不能收到
> 
> 我也是发送失败，返回“用户信息状态不合法”
> 
> 排查后发现是 pushplus的地址改了，将代码里 `pushPlusNotify` 的 post url 换成 `http://pushplus.hxtrip.com/send` 就发送成功了。
> 
> 另外问下这么多脚本为什么每个都单独跑 workflow，合并成一个不好么，太多重复性工作了，之前另一个库就是太多 action，执行几次后直接被 github 限额了。。。

限额是因为你把仓库设置成私有了，改成公开就行。
脚本可以合并，但为了综合考虑:
1 可以方便查看哪个脚本的运行日志
2 个别单脚本运行时间很长，长达数小时
3 action运行时间超过6小时会自动停止脚本

**Comment by BruceLee569** [comment]
> > > > 昨日收益， 目前在这个试了，会有这个问题。
> > > 
> > > 
> > > 这个脚本推送是没有问题了，因为我就是push+推送。
> > > 仔细看看是不是环境变量添加错误，如果是一对多推送，PUSH_PLUS_USER是填群组编号，不是填群组昵称。
> > > 如果还不行，先自己在push+官网手动发消息看看能不能收到
> > 
> > 
> > 我也是发送失败，返回“用户信息状态不合法”
> > 排查后发现是 pushplus的地址改了，将代码里 `pushPlusNotify` 的 post url 换成 `http://pushplus.hxtrip.com/send` 就发送成功了。
> > 另外问下这么多脚本为什么每个都单独跑 workflow，合并成一个不好么，太多重复性工作了，之前另一个库就是太多 action，执行几次后直接被 github 限额了。。。
> 
> 限额是因为你把仓库设置成私有了，改成公开就行。
> 脚本可以合并，但为了综合考虑:
> 1 可以方便查看哪个脚本的运行日志
> 2 个别单脚本运行时间很长，长达数小时
> 3 action运行时间超过6小时会自动停止脚本

嗯嗯 谢谢回复 公开之后密钥不会泄露吧。

**Comment by inoyna11** [comment]
> > > > > 昨日收益， 目前在这个试了，会有这个问题。
> > > > 
> > > > 
> > > > 这个脚本推送是没有问题了，因为我就是push+推送。
> > > > 仔细看看是不是环境变量添加错误，如果是一对多推送，PUSH_PLUS_USER是填群组编号，不是填群组昵称。
> > > > 如果还不行，先自己在push+官网手动发消息看看能不能收到
> > > 
> > > 
> > > 我也是发送失败，返回“用户信息状态不合法”
> > > 排查后发现是 pushplus的地址改了，将代码里 `pushPlusNotify` 的 post url 换成 `http://pushplus.hxtrip.com/send` 就发送成功了。
> > > 另外问下这么多脚本为什么每个都单独跑 workflow，合并成一个不好么，太多重复性工作了，之前另一个库就是太多 action，执行几次后直接被 github 限额了。。。
> > 
> > 
> > 限额是因为你把仓库设置成私有了，改成公开就行。
> > 脚本可以合并，但为了综合考虑:
> > 1 可以方便查看哪个脚本的运行日志
> > 2 个别单脚本运行时间很长，长达数小时
> > 3 action运行时间超过6小时会自动停止脚本
> 
> 嗯嗯 谢谢回复 公开之后密钥不会泄露吧。

不会。

**Comment by lijiaqigz** [comment]
变量检查过没有问题，在官网测试也没问题，但运行还是没有收到推送。
配置 BARK 可行。

**Comment by less-byte** [comment]
> > > 昨日收益， 目前在这个试了，会有这个问题。
> > 
> > 
> > 这个脚本推送是没有问题了，因为我就是push+推送。
> > 仔细看看是不是环境变量添加错误，如果是一对多推送，PUSH_PLUS_USER是填群组编号，不是填群组昵称。
> > 如果还不行，先自己在push+官网手动发消息看看能不能收到
> 
> 我也是发送失败，返回“用户信息状态不合法”
> 
> 排查后发现是 pushplus的地址改了，将代码里 `pushPlusNotify` 的 post url 换成 `http://pushplus.hxtrip.com/send` 就发送成功了。
> 
> 另外问下这么多脚本为什么每个都单独跑 workflow，合并成一个不好么，太多重复性工作了，之前另一个库就是太多 action，执行几次后直接被 github 限额了。。。

`pushPlusNotify`找不到，请问具体是在哪几个脚本！！！！谢谢谢谢！！！

**Comment by inoyna11** [comment]
> 变量检查过没有问题，在官网测试也没问题，但运行还是没有收到推送。
> 配置 BARK 可行。

push+推送是没有问题的，个别脚本的push+推送通知被我去掉了，因为我嫌太吵了，如果你需要哪个脚本通知，留言告诉我修改

**Comment by inoyna11** [comment]
> > > > 昨日收益， 目前在这个试了，会有这个问题。
> > > 
> > > 
> > > 这个脚本推送是没有问题了，因为我就是push+推送。
> > > 仔细看看是不是环境变量添加错误，如果是一对多推送，PUSH_PLUS_USER是填群组编号，不是填群组昵称。
> > > 如果还不行，先自己在push+官网手动发消息看看能不能收到
> > 
> > 
> > 我也是发送失败，返回“用户信息状态不合法”
> > 排查后发现是 pushplus的地址改了，将代码里 `pushPlusNotify` 的 post url 换成 `http://pushplus.hxtrip.com/send` 就发送成功了。
> > 另外问下这么多脚本为什么每个都单独跑 workflow，合并成一个不好么，太多重复性工作了，之前另一个库就是太多 action，执行几次后直接被 github 限额了。。。
> 
> `pushPlusNotify`找不到，请问具体是在哪几个脚本！！！！谢谢谢谢！！！

push+推送是没有问题的，个别脚本的push+推送通知被我去掉了，因为我嫌太吵了，如果你需要哪个脚本通知，留言告诉我修改

**Comment by lijiaqigz** [comment]
> > 变量检查过没有问题，在官网测试也没问题，但运行还是没有收到推送。
> > 配置 BARK 可行。
> 
> push+推送是没有问题的，个别脚本的push+推送通知被我去掉了，因为我嫌太吵了，如果你需要哪个脚本通知，留言告诉我修改

不妨碍使用，只是刚好碰上问题而已。
