### ISSUE TITLE
报错了！！！

### ISSUE THREAD

**Issue by Godfunc** [inoyna11/jd28#17]
❗️crazyJoy挂机, 错误!
TypeError: Cannot read property 'nickname' of undefined
    at /home/runner/work/jdee/jdee/jd_crazy_joy_coin.js:790:39
    at got.post.then.message (/home/runner/work/jdee/jdee/jd_crazy_joy_coin.js:816:5677)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

这是只有我一个人遇到吗？

**Comment by inoyna11** [comment]
> ❗️crazyJoy挂机, 错误!
> TypeError: Cannot read property 'nickname' of undefined
> at /home/runner/work/jdee/jdee/jd_crazy_joy_coin.js:790:39
> at got.post.then.message (/home/runner/work/jdee/jdee/jd_crazy_joy_coin.js:816:5677)
> at runMicrotasks ()
> at processTicksAndRejections (internal/process/task_queues.js:95:5)
> 
> 这是只有我一个人遇到吗？

已更新，手动同步下脚本
