### ISSUE TITLE
报错x2

### ISSUE THREAD

**Issue by Godfunc** [inoyna11/jd28#18]
❗️京东赚赚, 错误!
TypeError: Cannot read property 'nickname' of undefined
    at /home/runner/work/jdee/jdee/jd_jdzz.js:489:39
    at /home/runner/work/jdee/jdee/jd_jdzz.js:527:4587
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by inoyna11** [comment]
> ❗️京东赚赚, 错误!
> TypeError: Cannot read property 'nickname' of undefined
> at /home/runner/work/jdee/jdee/jd_jdzz.js:489:39
> at /home/runner/work/jdee/jdee/jd_jdzz.js:527:4587
> at processTicksAndRejections (internal/process/task_queues.js:95:5)

更新了，这个报错可以无视的，不影响脚本功能运行

**Comment by pengpenging** [comment]
> > ❗️京东赚赚, 错误!
> > TypeError: Cannot read property 'nickname' of undefined
> > at /home/runner/work/jdee/jdee/jd_jdzz.js:489:39
> > at /home/runner/work/jdee/jdee/jd_jdzz.js:527:4587
> > at processTicksAndRejections (internal/process/task_queues.js:95:5)
> 
> 更新了，这个报错可以无视的，不影响脚本功能运行

删除运行历史目录无法执行

**Comment by inoyna11** [comment]
> > > ❗️京东赚赚, 错误!
> > > TypeError: Cannot read property 'nickname' of undefined
> > > at /home/runner/work/jdee/jdee/jd_jdzz.js:489:39
> > > at /home/runner/work/jdee/jdee/jd_jdzz.js:527:4587
> > > at processTicksAndRejections (internal/process/task_queues.js:95:5)
> > 
> > 
> > 更新了，这个报错可以无视的，不影响脚本功能运行
> 
> 删除运行历史目录无法执行

先无视，等我更新
