### ISSUE TITLE
请问是每天自动的吗

### ISSUE THREAD

**Issue by x1737886903** [inoyna11/jd28#2]

**Comment by inoyna11** [comment]
是的

**Comment by x1737886903** [comment]
谢谢

**Comment by ilee-ui** [comment]
怎么更新大佬您的代码呢

**Comment by pengpenging** [comment]
> 是的

请问cookie好容易失效，只能经常相应更改吗？

**Comment by inoyna11** [comment]
使用脚本[扫码获取京东cookie]，第一时间进入运行日志，打开里面的链接扫码，cookie会自动推送到你所填的通知消息

**Comment by pengpenging** [comment]
扫码扫不出来，我先用手机号的方式登录获取cookie了，据说这种方式有效期是30天

**Comment by inoyna11** [comment]
> 扫码扫不出来，我先用手机号的方式登录获取cookie了，据说这种方式有效期是30天

现在的ck基本都是30天，只有少个别的是3个月有效期，跟账号有关
