### ISSUE TITLE
CITY_SHARECODES怎么获取

### ISSUE THREAD

**Issue by yaj806** [inoyna11/jd28#22]
CITY_SHARECODES怎么获取

**Comment by inoyna11** [comment]
> CITY_SHARECODES怎么获取

哪个脚本

**Comment by yaj806** [comment]
> > CITY_SHARECODES怎么获取
> 
> 哪个脚本

jd_city

**Comment by inoyna11** [comment]
> > > CITY_SHARECODES怎么获取
> > 
> > 
> > 哪个脚本
> 
> jd_city

这个脚本暂时没有环境变量的支持，等lxk0301更新吧
