### ISSUE TITLE
教程

### ISSUE THREAD

**Issue by ForStrong** [inoyna11/jd28#23]
有没有详细一点的教程呀？

**Comment by ForStrong** [comment]
自动同步教程:

一:点击导入仓库，URL框填写https://github.com/inoyna11/jd28 Repository Name填写仓库名字，点击绿色按钮，等待导入完成(不要把仓库设为私有，会运行失败)。

二:申请PAT，Note下面框随意填写，把 repo和workflow 两部分勾上即可。 点击最下方的创建，生成的PAT复制下来。

三:申请完毕后，在新仓库分支中点击Settings-Secrets-New secret，name填PAT，框里面填写你第二步复制的PAT,保存即可。 接着再点击New secret，name填JD_COOKIE，框里面填写你的账号cookie，多账号换行。

四:点击仓库的Code，把上方的Star点亮，完毕

跟着这四步走完之后，该怎么运行这些脚本

**Comment by Roc-egg** [comment]
star就已经运行了,你可以去Actions看下正在运行的工作流程

**Comment by wys206** [comment]
> star就已经运行了,你可以去Actions看下正在运行的工作流程

server推送设置完运行了一次，没有推送，肿么回事呀？

**Comment by waringhu** [comment]
详细的教程可以参考这里：https://mp.weixin.qq.com/s/7TgX50qYC_c4WfOS0PduDw
