### ISSUE TITLE
手机狂欢城2报错

### ISSUE THREAD

**Issue by lsq543658134** [inoyna11/jd28#24]
internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module '/home/runner/work/jd_doudou/jd_doudou/b_carnivalcity.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Error: Process completed with exit code 1.

**Comment by inoyna11** [comment]
> internal/modules/cjs/loader.js:888
> throw err;
> ^
> 
> Error: Cannot find module '/home/runner/work/jd_doudou/jd_doudou/b_carnivalcity.js'
> at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
> at Function.Module._load (internal/modules/cjs/loader.js:730:27)
> at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
> at internal/main/run_main_module.js:17:47 {
> code: 'MODULE_NOT_FOUND',
> requireStack: []
> }
> Error: Process completed with exit code 1.

这个脚本已经更新了，同步我的脚本后使用
