### ISSUE TITLE
城城分现金没有互助码

### ISSUE THREAD

**Issue by yleen** [inoyna11/jd28#26]
![image](https://user-images.githubusercontent.com/35679794/119617058-f6e8e600-be33-11eb-9ed1-05c303f32b97.png)

**Comment by yleen** [comment]
请问大佬，这个secret填写的互助码是给别人助力的码，不是填自己的码？是这样吗

**Comment by inoyna11** [comment]
> 请问大佬，这个secret填写的互助码是给别人助力的码，不是填自己的码？是这样吗

这个脚本暂时没有环境变量的支持，等lxk0301更新吧
