### ISSUE TITLE
请问大佬没有log怎么解决

### ISSUE THREAD

**Issue by xzw1108** [inoyna11/jd28#30]
Error: The log was not found. It may have been deleted based on retention settings.

**Comment by inoyna11** [comment]
> Error: The log was not found. It may have been deleted based on retention settings.

哪个脚本

**Comment by xzw1108** [comment]
所有的脚本都是这样的

**Comment by inoyna11** [comment]
> 所有的脚本都是这样的

是运行日志里面显示的这个？

**Comment by xzw1108** [comment]
![image](https://user-images.githubusercontent.com/17683648/119748804-3ee42900-be85-11eb-990e-7ee675e1570a.png)
是的

**Comment by inoyna11** [comment]
> ![image](https://user-images.githubusercontent.com/17683648/119748804-3ee42900-be85-11eb-990e-7ee675e1570a.png)
> 是的

你是网络不好吧，我刚刚去看你的仓库，运行并没有报错。
你用手机查看下试试
