### ISSUE TITLE
抽中原厂耳机

### ISSUE THREAD

**Issue by pengpenging** [inoyna11/jd28#31]
店铺大转盘中抽中原厂耳机 显示
 
 获得 原厂耳机。活动店铺ID：10101184

但是我根据店铺ID没找到相应的抽奖了解呀？抽了个寂寞嘛

**Comment by inoyna11** [comment]
> 店铺大转盘中抽中原厂耳机 显示
> 
> 获得 原厂耳机。活动店铺ID：10101184
> 
> 但是我根据店铺ID没找到相应的抽奖了解呀？抽了个寂寞嘛

这个是店铺套路，大部分需要你在他的店铺消费满1000才送耳机

**Comment by pengpenging** [comment]
> > 店铺大转盘中抽中原厂耳机 显示
> > 获得 原厂耳机。活动店铺ID：10101184
> > 但是我根据店铺ID没找到相应的抽奖了解呀？抽了个寂寞嘛
> 
> 这个是店铺套路，大部分需要你在他的店铺消费满1000才送耳机

气人哈 我以为中奖了

**Comment by lijiaqigz** [comment]
> 店铺大转盘中抽中原厂耳机 显示
> 
> 获得 原厂耳机。活动店铺ID：10101184
> 
> 但是我根据店铺ID没找到相应的抽奖了解呀？抽了个寂寞嘛

请教下，如何根据 店铺ID 去找到店铺？

**Comment by w3313003** [comment]
> > 店铺大转盘中抽中原厂耳机 显示
> > 获得 原厂耳机。活动店铺ID：10101184
> > 但是我根据店铺ID没找到相应的抽奖了解呀？抽了个寂寞嘛
> 
> 请教下，如何根据 店铺ID 去找到店铺？

`https://mall.jd.com/index-${shopId}.html`

**Comment by pengpenging** [comment]
> > 店铺大转盘中抽中原厂耳机 显示
> > 获得 原厂耳机。活动店铺ID：10101184
> > 但是我根据店铺ID没找到相应的抽奖了解呀？抽了个寂寞嘛
> 
> 请教下，如何根据 店铺ID 去找到店铺？


直接在京东app搜索框中输入店铺ID搜索即可

**Comment by lijiaqigz** [comment]
> > > 店铺大转盘中抽中原厂耳机 显示
> > > 获得 原厂耳机。活动店铺ID：10101184
> > > 但是我根据店铺ID没找到相应的抽奖了解呀？抽了个寂寞嘛
> > 
> > 
> > 请教下，如何根据 店铺ID 去找到店铺？
> 
> 直接在京东app搜索框中输入店铺ID搜索即可

学习了
