### ISSUE TITLE
美丽研究院脚本报错

### ISSUE THREAD

**Issue by 13071558875** [inoyna11/jd28#36]
请尝试换服务器ip或者设置"xinruimz-isv.isvjcloud.com"域名直连，或者自定义UA再次尝试(环境变量JD_USER_AGENT)\n\n`

**Comment by inoyna11** [comment]
> 请尝试换服务器ip或者设置"xinruimz-isv.isvjcloud.com"域名直连，或者自定义UA再次尝试(环境变量JD_USER_AGENT)\n\n`

这个脚本有问题，本地可以运行，ac跑不了
