### ISSUE TITLE
jd_try.js建议可以把goodFilters 和 minPrice 改为配置项

### ISSUE THREAD

**Issue by EvilDrag0n** [inoyna11/jd28#42]
京东试用建议可以把goodFilters 和 minPrice 改为配置项，
过滤项和最低价格改为自定义配置。
或可以自定义执行哪些脚本

**Comment by EvilDrag0n** [comment]
oo .没事了，代码里有，wiki里少了而已

**Comment by inoyna11** [comment]
> oo .没事了，代码里有，wiki里少了而已

刚看了一下，有4个变量，需要的话我加上。脚本里面的申请内容都是配置好的，修改价格的话中一些小玩意没啥用

自定义执行脚本的话感觉不太需要，你不用哪个脚本直接禁用就行了

**Comment by EvilDrag0n** [comment]
看到了，我更新一个pr。更新wiki的你看一下
