### ISSUE TITLE
删除历史运行日志出错

### ISSUE THREAD

**Issue by GDKVIP** [inoyna11/jd28#44]
Error: Must have admin rights to Repository.

**Comment by inoyna11** [comment]
> Error: Must have admin rights to Repository.

添加环境变量TOKEN    框里面填你的密钥

**Comment by jkluio78** [comment]
> > Error: Must have admin rights to Repository.
> 
> 添加环境变量TOKEN 框里面填你的密钥

请问密钥是什么？PAT？还是github的登录密码？

**Comment by jkluio78** [comment]
> > > > Error: Must have admin rights to Repository.
> > > 
> > > 
> > > 添加环境变量TOKEN 框里面填你的密钥
> > 
> > 
> > 请问密钥是什么？PAT？还是github的登录密码？
> 
> PAT

删除日志运行到显示Not Found是正常的吗？
![image](https://user-images.githubusercontent.com/74967641/119922499-7dbbd100-bfa2-11eb-9ce0-b8a2e358267f.png)

**Comment by inoyna11** [comment]
> > > > > Error: Must have admin rights to Repository.
> > > > 
> > > > 
> > > > 添加环境变量TOKEN 框里面填你的密钥
> > > 
> > > 
> > > 请问密钥是什么？PAT？还是github的登录密码？
> > 
> > 
> > PAT
> 
> 删除日志运行到显示Not Found是正常的吗？
> ![image](https://user-images.githubusercontent.com/74967641/119922499-7dbbd100-bfa2-11eb-9ce0-b8a2e358267f.png)

可能是一下子删除太多了，你在运行一次，如果没有报错就可以了

**Comment by jkluio78** [comment]
> > > > > > Error: Must have admin rights to Repository.
> > > > > 
> > > > > 
> > > > > 添加环境变量TOKEN 框里面填你的密钥
> > > > 
> > > > 
> > > > 请问密钥是什么？PAT？还是github的登录密码？
> > > 
> > > 
> > > PAT
> > 
> > 
> > 删除日志运行到显示Not Found是正常的吗？
> > ![image](https://user-images.githubusercontent.com/74967641/119922499-7dbbd100-bfa2-11eb-9ce0-b8a2e358267f.png)
> 
> 可能是一下子删除太多了，你在运行一次，如果没有报错就可以了

这次没有报错了，感谢！
