### ISSUE TITLE
星推官报错

### ISSUE THREAD

**Issue by 13071558875** [inoyna11/jd28#46]
Run node adolf_star.js
internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module '/home/runner/work/jd/jd/adolf_star.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Error: Process completed with exit code 1

**Comment by inoyna11** [comment]
> Run node adolf_star.js
> internal/modules/cjs/loader.js:888
> throw err;
> ^
> 
> Error: Cannot find module '/home/runner/work/jd/jd/adolf_star.js'
> at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
> at Function.Module._load (internal/modules/cjs/loader.js:730:27)
> at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
> at internal/main/run_main_module.js:17:47 {
> code: 'MODULE_NOT_FOUND',
> requireStack: []
> }
> Error: Process completed with exit code 1

同步我的仓库使用

**Comment by 13071558875** [comment]
我就是按照教程同步的呀

**Comment by inoyna11** [comment]
> 我就是按照教程同步的呀

在运行一遍试试

**Comment by 13071558875** [comment]
> > Run node adolf_star.js
> > internal/modules/cjs/loader.js:888
> > throw err;
> > ^
> > Error: Cannot find module '/home/runner/work/jd/jd/adolf_star.js'
> > at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
> > at Function.Module._load (internal/modules/cjs/loader.js:730:27)
> > at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
> > at internal/main/run_main_module.js:17:47 {
> > code: 'MODULE_NOT_FOUND',
> > requireStack: []
> > }
> > Error: Process completed with exit code 1
> 
> 同步我的仓库使用



> > 我就是按照教程同步的呀
> 
> 在运行一遍试试

谢谢

**Comment by pengpenging** [comment]
> > 我就是按照教程同步的呀
> 
> 在运行一遍试试

我这边的星推官同步之后里面没有运行的程序

**Comment by 13071558875** [comment]
> > 我就是按照教程同步的呀
> 
> 在运行一遍试试

始终不行，感觉缺少一个代码

**Comment by inoyna11** [comment]
> > > 我就是按照教程同步的呀
> > 
> > 
> > 在运行一遍试试
> 
> 始终不行，感觉缺少一个代码

星推官脚本是正常的，因为我设置的整点定时任务，只会在整点的时候才会运行脚本

**Comment by pengpenging** [comment]
> > > > 我就是按照教程同步的呀
> > > 
> > > 
> > > 在运行一遍试试
> > 
> > 
> > 始终不行，感觉缺少一个代码
> 
> 星推官脚本是正常的，因为我设置的整点定时任务，只会在整点的时候才会运行脚本

我的星推官里面是空的

**Comment by inoyna11** [comment]
> > > > > 我就是按照教程同步的呀
> > > > 
> > > > 
> > > > 在运行一遍试试
> > > 
> > > 
> > > 始终不行，感觉缺少一个代码
> > 
> > 
> > 星推官脚本是正常的，因为我设置的整点定时任务，只会在整点的时候才会运行脚本
> 
> 我的星推官里面是空的

现在同步我的脚本运行星推官，然后等1点整的时候进日志里看就知道了
