### ISSUE TITLE
瓜分20亿的任务都失败了

### ISSUE THREAD

**Issue by yaj806** [inoyna11/jd28#48]
瓜分20亿的任务都失败了

**Comment by inoyna11** [comment]
> 瓜分20亿的任务都失败了

修改了，先用之前的版本

**Comment by yaj806** [comment]
> > 瓜分20亿的任务都失败了
> 
> 修改了，先用之前的版本

收到，多谢，我之前提交了几个文件，都是增加了共享码的，有空加进去呢，或者有没有办法我本地修改了，同步时不覆盖

**Comment by inoyna11** [comment]
> > > 瓜分20亿的任务都失败了
> > 
> > 
> > 修改了，先用之前的版本
> 
> 收到，多谢，我之前提交了几个文件，都是增加了共享码的，有空加进去呢，或者有没有办法我本地修改了，同步时不覆盖

都加了，你看看还有没有需要的变量，继续发给我

**Comment by yaj806** [comment]
![image](https://user-images.githubusercontent.com/62924780/119910956-ef882080-bf8a-11eb-8193-4ef141a339c0.png)
怎么用老版本啊？你这个2小时同步一次，我换了老版本是不是还被同步啊

**Comment by yaj806** [comment]
> > > > 瓜分20亿的任务都失败了
> > > 
> > > 
> > > 修改了，先用之前的版本
> > 
> > 
> > 收到，多谢，我之前提交了几个文件，都是增加了共享码的，有空加进去呢，或者有没有办法我本地修改了，同步时不覆盖
> 
> 都加了，你看看还有没有需要的变量，继续发给我

好的，等我有空的时候，再看看代码里还缺哪些

**Comment by inoyna11** [comment]
> ![image](https://user-images.githubusercontent.com/62924780/119910956-ef882080-bf8a-11eb-8193-4ef141a339c0.png)
> 怎么用老版本啊？你这个2小时同步一次，我换了老版本是不是还被同步啊

那个脚本的老版本？好用的话我换掉

**Comment by yaj806** [comment]
> > ![image](https://user-images.githubusercontent.com/62924780/119910956-ef882080-bf8a-11eb-8193-4ef141a339c0.png)
> > 怎么用老版本啊？你这个2小时同步一次，我换了老版本是不是还被同步啊
> 
> 那个脚本的老版本？好用的话我换掉

你在二楼说先用之前的版本，我以为之前版本可以用的
