### ISSUE TITLE
企业微信应用不推送

### ISSUE THREAD

**Issue by GDKVIP** [inoyna11/jd28#5]
配置了QYWX_AM
格式如下：
ww479cadfqfe8c151f,MPKN9gX97w4e4b4h4u7u4i4i4i4iO6mN_dDedBFzqC5c,@all,1000002

但是不推送，请问是哪里填错了吗

**Comment by inoyna11** [comment]
晚上更新

**Comment by inoyna11** [comment]
大部分都加上了，手动同步下脚本，如果觉得哪个脚本没通知或者通知太多，联系我修改

**Comment by GDKVIP** [comment]
已经有推送了，但还有几个问题，比如618任务做不完全，互助码填写了仍然提示没添加互助码

> 大部分都加上了，手动同步下脚本，如果觉得哪个脚本没通知或者通知太多，联系我修改

**Comment by inoyna11** [comment]
> 已经有推送了，但还有几个问题，比如618任务做不完全，互助码填写了仍然提示没添加互助码
> 
> > 大部分都加上了，手动同步下脚本，如果觉得哪个脚本没通知或者通知太多，联系我修改

618活动默认不做加购物车任务，这是lxk0301脚本默认的，我无法修改。无法添加助力码是哪个脚本，我修改下

**Comment by GDKVIP** [comment]
> > 已经有推送了，但还有几个问题，比如618任务做不完全，互助码填写了仍然提示没添加互助码
> > > 大部分都加上了，手动同步下脚本，如果觉得哪个脚本没通知或者通知太多，联系我修改
> 
> 618活动默认不做加购物车任务，这是lxk0301脚本默认的，我无法修改。无法添加助力码是哪个脚本，我修改下

我大概看了下Action，按规则配置后，有些会提示没有，比如：
《开始获取城城领现金配置文件
共1个京东账号
您提供了0个账号的城城领现金助力码
脚本不会自动抽奖，建议活动快结束开启，默认关闭》

**Comment by GDKVIP** [comment]
不过这些东西，倒也无所谓

**Comment by inoyna11** [comment]
> > > 已经有推送了，但还有几个问题，比如618任务做不完全，互助码填写了仍然提示没添加互助码
> > > > 大部分都加上了，手动同步下脚本，如果觉得哪个脚本没通知或者通知太多，联系我修改
> > 
> > 
> > 618活动默认不做加购物车任务，这是lxk0301脚本默认的，我无法修改。无法添加助力码是哪个脚本，我修改下
> 
> 我大概看了下Action，按规则配置后，有些会提示没有，比如：
> 《开始获取城城领现金配置文件
> 共1个京东账号
> 您提供了0个账号的城城领现金助力码
> 脚本不会自动抽奖，建议活动快结束开启，默认关闭》

lxk0301后续的脚本都不提供github环境变量支持，所以只能使用脚本自带的助力码，个人使用这个脚本很难达到提现的门槛，脚本现在是默认给我助力，如果介意的话可以点击禁用脚本，等待活动时间结束，我会删除脚本。
另外，如果有使用方面的疑惑，可以留言给我
