### ISSUE TITLE
想问下那里的互助问题

### ISSUE THREAD

**Issue by 13071558875** [inoyna11/jd28#55]
是大家都在互相互助还是就是单单给别人助力呢？不知道能不能把大家的互助码综合在一起然后互助，就不用每天去弄了。小白提问

**Comment by inoyna11** [comment]
> 是大家都在互相互助还是就是单单给别人助力呢？不知道能不能把大家的互助码综合在一起然后互助，就不用每天去弄了。小白提问

部分脚本是账号内部互助，账号多的话豆子就多一点。
另外的脚本需要你添加环境变量使用助力，具体教程参照lxk0301环境变量合集配置你需要的变量
