### ISSUE TITLE
推送设置有详细点的步骤吗？

### ISSUE THREAD

**Issue by wys206** [inoyna11/jd28#56]
server酱的推送设置需要在sendNotify.js里添加SCKEY吗？为什么按照“注：此处设置github action用户填写到Settings-Secrets里面(Name输入PUSH_KEY)”收不到推送呢?

**Comment by inoyna11** [comment]
> server酱的推送设置需要在sendNotify.js里添加SCKEY吗？为什么按照“注：此处设置github action用户填写到Settings-Secrets里面(Name输入PUSH_KEY)”收不到推送呢?

在你填写cookie的地方在新建一个，Name输入PUSH_KEY，下面的框输入你的server酱的值

**Comment by lijiaqigz** [comment]
> server酱

server酱  升级了，推送 好像不行了。

**Comment by inoyna11** [comment]
> > server酱
> 
> server酱 升级了，推送 好像不行了。

可以用push+
