### ISSUE TITLE
萌宠任务做完了,金币没增加

### ISSUE THREAD

**Issue by g11g** [inoyna11/jd28#57]

**Comment by inoyna11** [comment]
> _No description provided._

东东萌宠的进度加的很慢，一件东西大概大半年左右才能拿到，具体看脚本运行日志，任务完成就行了

**Comment by g11g** [comment]
说错了,是动物联萌

**Comment by inoyna11** [comment]
> 说错了,是动物联萌

账号火爆的话做不了任务，等更新吧
