### ISSUE TITLE
能在readme里加上脚本的使用教程吗？

### ISSUE THREAD

**Issue by chan1108** [inoyna11/jd28#6]
不知道该怎么使用

**Comment by inoyna11** [comment]
> 不知道该怎么使用

已经更新cookie获取教程，手动同步下脚本

**Comment by chan1108** [comment]
> > 不知道该怎么使用
> 
> 已经更新cookie获取教程，手动同步下脚本

我的意思是能让这脚本跑起来的教程，cookies我会获取，但是这个脚本是第一次接触，对docker不熟

**Comment by GNAFUIL** [comment]
你按照他的步骤做完就跑起来了，自动部署在Github action里面，要通知就在Secrets里面加上就行，想改变什么变量也在Secrets里面加

**Comment by chan1108** [comment]
> 你按照他的步骤做完就跑起来了，自动部署在Github action里面，要通知就在Secrets里面加上就行，想改变什么变量也在Secrets里面加

哦哦，明白了，谢谢
