### ISSUE TITLE
新增账号cookie后，原账号不能自动完成萌宠任务

### ISSUE THREAD

**Issue by HShokaku** [inoyna11/jd28#60]
今天新增加了一个京东账号的cookie，新的账号可以自动完成任务，但原本的账号不能自动完成萌宠任务（也没有注销原账号，新账号是在无痕模式下获取的cookie）

**Comment by inoyna11** [comment]
> 今天新增加了一个京东账号的cookie，新的账号可以自动完成任务，但原本的账号不能自动完成萌宠任务（也没有注销原账号，新账号是在无痕模式下获取的cookie）

我刚刚看了你的运行日志

【提示】京东账号1*
萌宠活动未开启
请手动去京东APP开启活动
入口：我的->游戏与互动->查看更多开启

活动需要手动开启的

**Comment by HShokaku** [comment]
十分抱歉，我的描述有点问题，误把瓜分20亿的活动描述成萌宠任务了

**Comment by inoyna11** [comment]
> 十分抱歉，我的描述有点问题，误把瓜分20亿的活动描述成萌宠任务了

账号火爆了做不了任务

**Comment by HShokaku** [comment]
> > 十分抱歉，我的描述有点问题，误把瓜分20亿的活动描述成萌宠任务了
> 
> 账号火爆了做不了任务

好的，十分感谢！
