### ISSUE TITLE
自动同步和joy挂机一直错误 是哪里出问题了吗？

### ISSUE THREAD

**Issue by xdeancc** [inoyna11/jd28#62]
用仓库挂的脚本
![QQ截图20210528201155](https://user-images.githubusercontent.com/55089420/119982330-47597280-bff1-11eb-8c7f-113243491823.png)

**Comment by inoyna11** [comment]
> 用仓库挂的脚本
> ![QQ截图20210528201155](https://user-images.githubusercontent.com/55089420/119982330-47597280-bff1-11eb-8c7f-113243491823.png)



> 用仓库挂的脚本
> ![QQ截图20210528201155](https://user-images.githubusercontent.com/55089420/119982330-47597280-bff1-11eb-8c7f-113243491823.png)

不要fork使用，同步错误是你没有添加密钥，joy挂机脚本是一直循环的，action限制单脚本运行时间是6小时，所以6小时后会自动停止脚本

**Comment by xdeancc** [comment]
> > 用仓库挂的脚本
> > ![QQ截图20210528201155](https://user-images.githubusercontent.com/55089420/119982330-47597280-bff1-11eb-8c7f-113243491823.png)
> 
> 
> 
> > 用仓库挂的脚本
> > ![QQ截图20210528201155](https://user-images.githubusercontent.com/55089420/119982330-47597280-bff1-11eb-8c7f-113243491823.png)
> 
> 不要fork使用，同步错误是你没有添加密钥，joy挂机脚本是一直循环的，action限制单脚本运行时间是6小时，所以6小时后会自动停止脚本

没有fork使用，按照教程一步一步来的，密钥？是那个密钥？PAT吗？我添加了呀。。

**Comment by xdeancc** [comment]
> > > > 用仓库挂的脚本
> > > > ![QQ截图20210528201155](https://user-images.githubusercontent.com/55089420/119982330-47597280-bff1-11eb-8c7f-113243491823.png)
> > > 
> > > 
> > > > 用仓库挂的脚本
> > > > ![QQ截图20210528201155](https://user-images.githubusercontent.com/55089420/119982330-47597280-bff1-11eb-8c7f-113243491823.png)
> > > 
> > > 
> > > 不要fork使用，同步错误是你没有添加密钥，joy挂机脚本是一直循环的，action限制单脚本运行时间是6小时，所以6小时后会自动停止脚本
> > 
> > 没有fork使用，按照教程一步一步来的，密钥？是那个密钥？PAT吗？我添加了呀。。
> 
> 删除仓库重新按照教程来，不要把仓库设置为私有

我寻思也妹有设为私有啊，明天删库从新来吧😂😂

**Comment by jkluio78** [comment]
> > > > > 用仓库挂的脚本
> > > > > ![QQ截图20210528201155](https://user-images.githubusercontent.com/55089420/119982330-47597280-bff1-11eb-8c7f-113243491823.png)
> > > > 
> > > > 
> > > > > 用仓库挂的脚本
> > > > > ![QQ截图20210528201155](https://user-images.githubusercontent.com/55089420/119982330-47597280-bff1-11eb-8c7f-113243491823.png)
> > > > 
> > > > 
> > > > 不要fork使用，同步错误是你没有添加密钥，joy挂机脚本是一直循环的，action限制单脚本运行时间是6小时，所以6小时后会自动停止脚本
> > > 
> > > 
> > > 没有fork使用，按照教程一步一步来的，密钥？是那个密钥？PAT吗？我添加了呀。。
> > 
> > 
> > 删除仓库重新按照教程来，不要把仓库设置为私有
> 
> 我寻思也妹有设为私有啊，明天删库从新来吧😂😂

你试下新建一个Secret，名字是TOKEN，值是PAT的值，再运行一下删除日志看看，如果有删除记录但仍然出现error，说明你积攒的日志太多了，多运行几次就没有error了

**Comment by 18538568803** [comment]
> > 用仓库挂的脚本
> > ![QQ截图20210528201155](https://user-images.githubusercontent.com/55089420/119982330-47597280-bff1-11eb-8c7f-113243491823.png)
> 
> > 用仓库挂的脚本
> > ![QQ截图20210528201155](https://user-images.githubusercontent.com/55089420/119982330-47597280-bff1-11eb-8c7f-113243491823.png)
> 
> 不要fork使用，同步错误是你没有添加密钥，joy挂机脚本是一直循环的，action限制单脚本运行时间是6小时，所以6小时后会自动停止脚本

请问不fork如何和您的代码保持同步

**Comment by inoyna11** [comment]
> > > 用仓库挂的脚本
> > > ![QQ截图20210528201155](https://user-images.githubusercontent.com/55089420/119982330-47597280-bff1-11eb-8c7f-113243491823.png)
> > 
> > 
> > > 用仓库挂的脚本
> > > ![QQ截图20210528201155](https://user-images.githubusercontent.com/55089420/119982330-47597280-bff1-11eb-8c7f-113243491823.png)
> > 
> > 
> > 不要fork使用，同步错误是你没有添加密钥，joy挂机脚本是一直循环的，action限制单脚本运行时间是6小时，所以6小时后会自动停止脚本
> 
> 请问不fork如何和您的代码保持同步

按照教程来，最后就可以自动同步了

**Comment by xdeancc** [comment]
> > > > > > 用仓库挂的脚本
> > > > > > ![QQ截图20210528201155](https://user-images.githubusercontent.com/55089420/119982330-47597280-bff1-11eb-8c7f-113243491823.png)
> > > > > 
> > > > > 
> > > > > > 用仓库挂的脚本
> > > > > > ![QQ截图20210528201155](https://user-images.githubusercontent.com/55089420/119982330-47597280-bff1-11eb-8c7f-113243491823.png)
> > > > > 
> > > > > 
> > > > > 不要fork使用，同步错误是你没有添加密钥，joy挂机脚本是一直循环的，action限制单脚本运行时间是6小时，所以6小时后会自动停止脚本
> > > > 
> > > > 
> > > > 没有fork使用，按照教程一步一步来的，密钥？ 是那个密钥？ PAT吗？ 我添加了呀。。
> > > 
> > > 
> > > 删除仓库重新按照教程来，不要把仓库设置为私有
> > 
> > 
> > 我寻思也妹有设为私有啊，明天删库从新来吧😂😂
> 
> 你试下新建一个Secret，名字是TOKEN，值是PAT的值，再运行一下删除日志看看，如果有删除记录但仍然出现error，说明你积攒的日志太多了，多运行几次就没有error了

新建了一个token，然后运行了删除日志，自动同步就可以用了，谢谢大佬
