### ISSUE TITLE
手机狂欢城日志显示正常，但实际没有完成

### ISSUE THREAD

**Issue by Dron1sh** [inoyna11/jd28#64]
![image](https://user-images.githubusercontent.com/9458105/120054781-9f7d8c80-c064-11eb-90c8-b509ec58db65.png)

脚本以同步最新，部分号存在问题

**Comment by inoyna11** [comment]
> ![image](https://user-images.githubusercontent.com/9458105/120054781-9f7d8c80-c064-11eb-90c8-b509ec58db65.png)
> 
> 脚本以同步最新，部分号存在问题

确认你那没完成任务的号是否存在黑号的情况，我正常号使用没问题

**Comment by Dron1sh** [comment]
> > ![image](https://user-images.githubusercontent.com/9458105/120054781-9f7d8c80-c064-11eb-90c8-b509ec58db65.png)
> > 脚本以同步最新，部分号存在问题
> 
> 确认你那没完成任务的号是否存在黑号的情况，我正常号使用没问题

京东怎么查黑号

**Comment by inoyna11** [comment]
> > > ![image](https://user-images.githubusercontent.com/9458105/120054781-9f7d8c80-c064-11eb-90c8-b509ec58db65.png)
> > > 脚本以同步最新，部分号存在问题
> > 
> > 
> > 确认你那没完成任务的号是否存在黑号的情况，我正常号使用没问题
> 
> 京东怎么查黑号

看你京喜工厂或者农场能不能生产就知道了
