### ISSUE TITLE
想问下cookies问题

### ISSUE THREAD

**Issue by 13071558875** [inoyna11/jd28#65]
我三个号只有第一个号的cookies时间有一个月，另外两个号都是一阵子就没，差不多一个小时那样，有朋友是一样的吗？是jd最近改了cookies的有效时间吗

**Comment by inoyna11** [comment]
> 我三个号只有第一个号的cookies时间有一个月，另外两个号都是一阵子就没，差不多一个小时那样，有朋友是一样的吗？是jd最近改了cookies的有效时间吗

没有改，是你ck获取方式错误     按照我的手机获取ck方式去获取就可以了

**Comment by 13071558875** [comment]
> > 我三个号只有第一个号的cookies时间有一个月，另外两个号都是一阵子就没，差不多一个小时那样，有朋友是一样的吗？是jd最近改了cookies的有效时间吗
> 
> 没有改，是你ck获取方式错误 按照我的手机获取ck方式去获取就可以了

我两个都试过了，只有早期那个在电脑上获取的可以一个月

**Comment by inoyna11** [comment]
> > > 我三个号只有第一个号的cookies时间有一个月，另外两个号都是一阵子就没，差不多一个小时那样，有朋友是一样的吗？是jd最近改了cookies的有效时间吗
> > 
> > 
> > 没有改，是你ck获取方式错误 按照我的手机获取ck方式去获取就可以了
> 
> 我两个都试过了，只有早期那个在电脑上获取的可以一个月

手机获取的时候必须要用手机验证码登陆，其他方式都是几个小时。
如果还不行的话把京东密码改了，然后在获取
