### ISSUE TITLE
脚本自动获取全部优惠券吗，还是要准点自己领

### ISSUE THREAD

**Issue by zhangxs3** [inoyna11/jd28#68]

**Comment by zhangxs3** [comment]
还有加入购物车的商品怎么通过脚本取消

**Comment by inoyna11** [comment]
> 还有加入购物车的商品怎么通过脚本取消

脚本并不是获取全部全部的券，只会根据一会任务奖励或者任务要求获得优惠券。
购物车的商品不能用脚本取消，手动半分钟就删除了
