### ISSUE TITLE
火爆账号有办法解吗

### ISSUE THREAD

**Issue by XiaokangLi** [inoyna11/jd28#69]
放上去4个号 一个就火爆了  不会自动做618任务  其他号都正常  郁闷

**Comment by inoyna11** [comment]
> 放上去4个号 一个就火爆了 不会自动做618任务 其他号都正常 郁闷

暂时没有，先手动做下吧

**Comment by lucF333** [comment]
> > 放上去4个号 一个就火爆了 不会自动做618任务 其他号都正常 郁闷
> 
> 暂时没有，先手动做下吧

https://ws28.cn/f/5jgx7u9kazs 
我大号用这个AutoJs的不会提示火爆，但滑稽东和这里都会提示。52pj@insen的脚本应该可以参考修改一下参数

**Comment by yaj806** [comment]
> > > 放上去4个号 一个就火爆了 不会自动做618任务 其他号都正常 郁闷
> > 
> > 
> > 暂时没有，先手动做下吧
> 
> https://ws28.cn/f/5jgx7u9kazs
> 我大号用这个AutoJs的不会提示火爆，但滑稽东和这里都会提示。52pj@insen的脚本应该可以参考修改一下参数

这个脚本怎么执行啊

**Comment by lucF333** [comment]
> > > > 放上去4个号 一个就火爆了 不会自动做618任务 其他号都正常 郁闷
> > > 
> > > 
> > > 暂时没有，先手动做下吧
> > 
> > 
> > https://ws28.cn/f/5jgx7u9kazs
> > 我大号用这个AutoJs的不会提示火爆，但滑稽东和这里都会提示。52pj@insen的脚本应该可以参考修改一下参数
> 
> 这个脚本怎么执行啊

https://www.52pojie.cn/thread-1354251-1-1.html
可以看这个贴子，要用安卓，会自动更新获取活动脚本。我上面发的是这次618活动的代码，不能直接运行
