### ISSUE TITLE
天天加速脚本运行失败

### ISSUE THREAD

**Issue by tinpont** [inoyna11/jd28#7]
日志如下：
```
Run node jd_speed.js

🔔✈️天天加速, 开始!

====================共有1个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：5/24/2021, 5:58:42 PM=====================


开始【京东账号1】xxx


天天加速任务进行中

==============📣系统通知📣==============
京东天天-加速TypeError‼️
{}
Cannot read property 'isLogin' of undefined




🔔✈️天天加速, 结束! 🕛 1.72 秒
```

**Comment by inoyna11** [comment]
> 日志如下：
> 
> ```
> Run node jd_speed.js
> 
> 🔔✈️天天加速, 开始!
> 
> ====================共有1个京东账号Cookie=========
> 
> ==================脚本执行- 北京时间(UTC+8)：5/24/2021, 5:58:42 PM=====================
> 
> 
> 开始【京东账号1】xxx
> 
> 
> 天天加速任务进行中
> 
> ==============📣系统通知📣==============
> 京东天天-加速TypeError‼️
> {}
> Cannot read property 'isLogin' of undefined
> 
> 
> 
> 
> 🔔✈️天天加速, 结束! 🕛 1.72 秒
> ```

同步下脚本，在运行次试试

**Comment by Roc-egg** [comment]
一样的错误，大佬你的actions看到也是这个错误

**Comment by stephenjack2028** [comment]
哪儿看日志啊？谢谢

**Comment by stephenjack2028** [comment]
> 日志如下：
> 
> ```
> Run node jd_speed.js
> 
> 🔔✈️天天加速, 开始!
> 
> ====================共有1个京东账号Cookie=========
> 
> ==================脚本执行- 北京时间(UTC+8)：5/24/2021, 5:58:42 PM=====================
> 
> 
> 开始【京东账号1】xxx
> 
> 
> 天天加速任务进行中
> 
> ==============📣系统通知📣==============
> 京东天天-加速TypeError‼️
> {}
> Cannot read property 'isLogin' of undefined
> 
> 
> 
> 
> 🔔✈️天天加速, 结束! 🕛 1.72 秒
> ```

怎么看日志的，谢谢

**Comment by inoyna11** [comment]
> > 日志如下：
> > ```
> > Run node jd_speed.js
> > 
> > 🔔✈️天天加速, 开始!
> > 
> > ====================共有1个京东账号Cookie=========
> > 
> > ==================脚本执行- 北京时间(UTC+8)：5/24/2021, 5:58:42 PM=====================
> > 
> > 
> > 开始【京东账号1】xxx
> > 
> > 
> > 天天加速任务进行中
> > 
> > ==============📣系统通知📣==============
> > 京东天天-加速TypeError‼️
> > {}
> > Cannot read property 'isLogin' of undefined
> > 
> > 
> > 
> > 
> > 🔔✈️天天加速, 结束! 🕛 1.72 秒
> > ```
> 
> 怎么看日志的，谢谢

已更新

**Comment by inoyna11** [comment]
> 一样的错误，大佬你的actions看到也是这个错误

已更新

**Comment by tinpont** [comment]
@stephenjack2028 在action里面，左边有对应的任务，点开可以看到右边执行的时间。随便点开一个，日志就在里面。刚手动执行了，没问题了。
