### ISSUE TITLE
那个申请店铺入会怎么设置呢

### ISSUE THREAD

**Issue by X199X** [inoyna11/jd28#70]
![Screenshot_2021-05-29-23-59-21-056_com android chrome](https://user-images.githubusercontent.com/85023915/120076847-38022400-c0da-11eb-8c54-86d8a1d5d2b3.jpg)

**Comment by inoyna11** [comment]
脚本默认不开通会员，默认不加购商品。环境变量 export ADOLF_ADDSKU="true"//执行加购任务环境变量 export ADOLF_MARTIN="true"//执行入会任务
