### ISSUE TITLE
口袋书店任务没有完成到

### ISSUE THREAD

**Issue by 13071558875** [inoyna11/jd28#74]
我已经开启了口袋书店，但是任务依然没有跑到，我是要更新一下cookie吗
🔔口袋书店, 结束! 🕛 5.129

**Comment by inoyna11** [comment]
> 我已经开启了口袋书店，但是任务依然没有跑到，我是要更新一下cookie吗
> 🔔口袋书店, 结束! 🕛 5.129

可以了，更新下脚本   然后手动进入
首页-更多频道-京东图书-右上角签到-底部进入活动，然后手动做几个任务在跑脚本

**Comment by jkluio78** [comment]
> > 我已经开启了口袋书店，但是任务依然没有跑到，我是要更新一下cookie吗
> > 🔔口袋书店, 结束! 🕛 5.129
> 
> 可以了，更新下脚本 然后手动进入
> 首页-更多频道-京东图书-右上角签到-底部进入活动，然后手动做几个任务在跑脚本

大佬，我这里跑**赢一加新品手机**和**飞利浦电视成长记**，日志也是空白
![image](https://user-images.githubusercontent.com/74967641/120168841-e8cf0700-c231-11eb-8b2a-572c71c4103a.png)
![image](https://user-images.githubusercontent.com/74967641/120168808-df459f00-c231-11eb-8211-746143133a3e.png)

还有**蒙牛有机牧场**，虽然有日志，但是我在京东app里面没找到。这几个活动是在网页进行的吗？

**Comment by inoyna11** [comment]
> > > 我已经开启了口袋书店，但是任务依然没有跑到，我是要更新一下cookie吗
> > > 🔔口袋书店, 结束! 🕛 5.129
> > 
> > 
> > 可以了，更新下脚本 然后手动进入
> > 首页-更多频道-京东图书-右上角签到-底部进入活动，然后手动做几个任务在跑脚本
> 
> 大佬，我这里跑**赢一加新品手机**和**飞利浦电视成长记**，日志也是空白
> ![image](https://user-images.githubusercontent.com/74967641/120168841-e8cf0700-c231-11eb-8b2a-572c71c4103a.png)
> ![image](https://user-images.githubusercontent.com/74967641/120168808-df459f00-c231-11eb-8211-746143133a3e.png)
> 
> 还有**蒙牛有机牧场**，虽然有日志，但是我在京东app里面没找到。这几个活动是在网页进行的吗？

同步脚本，在运行一次
