### ISSUE TITLE
删除历史运行日志 报错

### ISSUE THREAD

**Issue by 18538568803** [inoyna11/jd28#76]
提示Run smallprogram/delete-workflow-runs@main
Error: Must have admin rights to Repository.

**Comment by inoyna11** [comment]
> 提示Run smallprogram/delete-workflow-runs@main
> Error: Must have admin rights to Repository.

不要fork    按照教程同步脚本来使用

**Comment by 18538568803** [comment]
> > 提示运行 smallprogram/delete-workflow-runs@main
> > 错误：必须具有存储库的管理员权限。
> 
> 切忌 for k 按照教程同步脚本来使用

没有fork,照着教程来的

**Comment by w3313003** [comment]
> > > 提示运行 smallprogram/delete-workflow-runs@main
> > > 错误：必须具有存储库的管理员权限。
> > 
> > 
> > 切忌 for k 按照教程同步脚本来使用
> 
> 没有fork,照着教程来的

actions secrets 里面添加一个TOKEN 值是PAT
