### ISSUE TITLE
想请问如何更新脚本？

### ISSUE THREAD

**Issue by zhangft7478191** [inoyna11/jd28#77]
没有按fork方式，按照教程来的。但目前看到并没有自动同步代码 https://github.com/zhangft7478191/jdscript

**Comment by inoyna11** [comment]
> 没有按fork方式，按照教程来的。但目前看到并没有自动同步代码 https://github.com/zhangft7478191/jdscript

应该是PAT填错了，重新申请PAT填进去  然后在手动同步下脚本

**Comment by inoyna11** [comment]
> > 没有按fork方式，按照教程来的。但目前看到并没有自动同步代码 https://github.com/zhangft7478191/jdscript
> 
> 应该是PAT填错了，重新申请PAT填进去 然后在手动同步下脚本

Note下面框随意填写，把 repo和workflow 两部分勾上即可。   这2部分必须要勾上

**Comment by zhangft7478191** [comment]
> > 没有按fork方式，按照教程来的。但目前看到并没有自动同步代码https://github.com/zhangft7478191/jdscript
> 
> 应该是PAT填错了，重申请PAT填进去然后在手动同步下

想请问手动同步是怎么同步呀，谢谢！

**Comment by inoyna11** [comment]
> > > 没有按fork方式，按照教程来的。但目前看到并没有自动同步代码https://github.com/zhangft7478191/jdscript
> > 
> > 
> > 应该是PAT填错了，重申请PAT填进去然后在手动同步下
> 
> 想请问手动同步是怎么同步呀，谢谢！

点击actions    到里面选择同步，然后手动运行

**Comment by zhangft7478191** [comment]
> > > > 没有按fork方式，按照教程来的。但目前看到并没有自动同步代码https://github.com/zhangft7478191/jdscript
> > > 
> > > 
> > > 应该是PAT填错了，重申请PAT填进去然后在手动同步下
> > 
> > 
> > 想请问手动同步是怎么同步呀，谢谢！
> 
> 点击actions 到里面选择同步，然后手动运行

找到了，同步成功！感谢！
想问下，cookie有效期是1个月，那需要我每个月都要获取并修改一次吗？

**Comment by inoyna11** [comment]
> > > > > 没有按fork方式，按照教程来的。但目前看到并没有自动同步代码https://github.com/zhangft7478191/jdscript
> > > > 
> > > > 
> > > > 应该是PAT填错了，重申请PAT填进去然后在手动同步下
> > > 
> > > 
> > > 想请问手动同步是怎么同步呀，谢谢！
> > 
> > 
> > 点击actions 到里面选择同步，然后手动运行
> 
> 找到了，同步成功！感谢！
> 想问下，cookie有效期是1个月，那需要我每个月都要获取并修改一次吗？

是的

**Comment by zhangft7478191** [comment]
> > > > > > 没有按fork方式，按照教程来的。但目前看到并没有自动同步代码https://github.com/zhangft7478191/jdscript
> > > > > 
> > > > > 
> > > > > 应该是PAT填错了，重申请PAT填进去然后在手动同步下
> > > > 
> > > > 
> > > > 想请问手动同步是怎么同步呀，谢谢！
> > > 
> > > 
> > > 点击actions 到里面选择同步，然后手动运行
> > 
> > 
> > 找到了，同步成功！感谢！
> > 想问下，cookie有效期是1个月，那需要我每个月都要获取并修改一次吗？
> 
> 是的

感谢！！！
