### ISSUE TITLE
哪儿查看执行后的日志

### ISSUE THREAD

**Issue by stephenjack2028** [inoyna11/jd28#8]
哪儿查看执行后的日志，还有每天自动运行吗？啥时候运行

**Comment by stephenjack2028** [comment]
i know

**Comment by inoyna11** [comment]
> 哪儿查看执行后的日志，还有每天自动运行吗？啥时候运行

在actions，选择需要查看的脚本，进去后点击build就可以看到。
脚本是每天自动运行的，只需要按教程添加cookie即可
