### ISSUE TITLE
欢乐挂机任务显示 joy信息获取失败.有啥解决办法吗？

### ISSUE THREAD

**Issue by Rebirthzero** [inoyna11/jd28#81]
![Screenshot_20210531-202652](https://user-images.githubusercontent.com/82878440/120195168-05c70280-c251-11eb-87b4-23897dccd4e2.jpg)

**Comment by Rebirthzero** [comment]
欢乐挂机点开任务详细.里面显示joy信息获取失败.当前京东豆值也不能获取.每次任务结束后都失败了.应该怎么解决？

**Comment by Rebirthzero** [comment]
![Uploading Screenshot_20210531-205141.jpg…]()

**Comment by Rebirthzero** [comment]
![Screenshot_20210531-205141](https://user-images.githubusercontent.com/82878440/120196325-4ecb8680-c252-11eb-8d87-ae8f8b84ccaa.jpg)
任务结束后显示任务失败.是不是就是跟那个joy信息获取失败有关？

**Comment by inoyna11** [comment]
> ![Screenshot_20210531-205141](https://user-images.githubusercontent.com/82878440/120196325-4ecb8680-c252-11eb-8d87-ae8f8b84ccaa.jpg)
> 任务结束后显示任务失败.是不是就是跟那个joy信息获取失败有关？

获取失败是号的问题，但是不影响金币的增加，只是显示不出来具体的数量。
失败是因为这个挂机是无限循环的，但是actions单个脚本最多只能运行6个小时，超过时间会自动停止

**Comment by Rebirthzero** [comment]
所以就是说那个任务失败可以忽略.属于正常现象对吧

**Comment by Rebirthzero** [comment]
> > ![截图_20210531-205141](https://user-images.githubusercontent.com/82878440/120196325-4ecb8680-c252-11eb-8d87-ae8f8b84ccaa.jpg)
> > 任务结束后显示任务失败。是不是就是跟那个joy信息获取失败有关？
> 
> 获取失败是号的问题，但是不影响金币的增加，只是显示不出来具体的数量。
> 失败是因为这个挂机是无限循环的，但是动作最多只能运行6小时，超过时间会自动停止

**Comment by inoyna11** [comment]
> > > ![截图_20210531-205141](https://user-images.githubusercontent.com/82878440/120196325-4ecb8680-c252-11eb-8d87-ae8f8b84ccaa.jpg)
> > > 任务结束后显示任务失败。是不是就是跟那个joy信息获取失败有关？
> > 
> > 
> > 获取失败是号的问题，但是不影响金币的增加，只是显示不出来具体的数量。
> > 失败是因为这个挂机是无限循环的，但是动作最多只能运行6小时，超过时间会自动停止
> 
> 就是说那个失败任务失败和获取失败都可以忽略.属于正常现象对吧？

是的

**Comment by Rebirthzero** [comment]
> > > > ![截图_20210531-205141](https://user-images.githubusercontent.com/82878440/120196325-4ecb8680-c252-11eb-8d87-ae8f8b84ccaa.jpg)
> > > > 任务结束后显示任务失败。是不是就是跟那个那个joy信息获取失败有关？
> > > 
> > > 
> > > 获取失败是号的问题，但不影响金币的增加，只是显示不出来具体的数量。
> > > 失败是因为这个挂机是无限循环的，但是动态最多只能持续6小时，超过时间会自动停止
> > 
> > 
> > 就是说那个失败任务失败和获取失败都可以忽略。属于正常现象对吧？
> 
> 是的
好的.谢谢大佬
