### ISSUE TITLE
Cookie不对

### ISSUE THREAD

**Issue by Tongmengjun** [inoyna11/jd28#85]
每次填上cookie都显示失效，不是检查里面获取的？填了好几个账号的都是失效

**Comment by Tongmengjun** [comment]
cookie需要填哪些内容？我是直接全部复制进去的

**Comment by Tongmengjun** [comment]
> 每次填上cookie都显示失效，不是检查里面获取的？填了好几个账号的都是失效

**Comment by inoyna11** [comment]
> 每次填上cookie都显示失效，不是检查里面获取的？填了好几个账号的都是失效

按照手机获取cookie教程去获取

**Comment by Tongmengjun** [comment]
> > 每次填上cookie都显示失效，不是检查里面获取的？填了好几个账号的都是失效
> 
> 按照手机获取cookie教程去获取

电脑上不行吗？edge用那个Cookie Edit搜出来的是pin和userkey，是一样的吗？
