### ISSUE TITLE
已经在Environments这个里面部署了环境，互助码没有生效

### ISSUE THREAD

**Issue by xdeancc** [inoyna11/jd28#86]
是我部署出错了吗？还是地方填错了
![部署](https://user-images.githubusercontent.com/55089420/120274349-4a4eae80-c2e2-11eb-8d43-a85c55333296.png)

**Comment by inoyna11** [comment]
> 是我部署出错了吗？还是地方填错了
> ![部署](https://user-images.githubusercontent.com/55089420/120274349-4a4eae80-c2e2-11eb-8d43-a85c55333296.png)

哪个脚本

**Comment by xdeancc** [comment]
> > 是我部署出错了吗？ 还是地方填错了
> > ![部署](https://user-images.githubusercontent.com/55089420/120274349-4a4eae80-c2e2-11eb-8d43-a85c55333296.png)
> 
> 哪个脚本

东东农场  fru开头的那个

**Comment by inoyna11** [comment]
> > > 是我部署出错了吗？ 还是地方填错了
> > > ![部署](https://user-images.githubusercontent.com/55089420/120274349-4a4eae80-c2e2-11eb-8d43-a85c55333296.png)
> > 
> > 
> > 哪个脚本
> 
> 东东农场 fru开头的那个

格式按照你下面填JD_COOKIE一样，name填FRUITSHARECODES,框里面填你的互助码

**Comment by xdeancc** [comment]
> > > > 是我部署出错了吗？ 还是地方填错了
> > > > ![部署](https://user-images.githubusercontent.com/55089420/120274349-4a4eae80-c2e2-11eb-8d43-a85c55333296.png)
> > > 
> > > 
> > > 哪个脚本
> > 
> > 
> > 东东农场 fru开头的那个
> 
> 格式按照你下面填JD_COOKIE一样，name填FRUITSHARECODES,框里面填你的互助码

我就是这么填的，但是没有生效，所以觉得奇怪

**Comment by inoyna11** [comment]
> 是我部署出错了吗？还是地方填错了
> ![部署](https://user-images.githubusercontent.com/55089420/120274349-4a4eae80-c2e2-11eb-8d43-a85c55333296.png)

Settings-Secrets-New secret     在这里填

**Comment by xdeancc** [comment]
> > 是我部署出错了吗？还是地方填错了
> > ![部署](https://user-images.githubusercontent.com/55089420/120274349-4a4eae80-c2e2-11eb-8d43-a85c55333296.png)
> 
> Settings-Secrets-New secret 在这里填

嗯嗯，好的  ，这就去试试看
