### ISSUE TITLE
报告！[618抽盲盒赢千万京豆/美丽研究院] 失效 

### ISSUE THREAD

**Issue by rececece** [inoyna11/jd28#88]
报告，618抽盲盒的美丽研究院报错，好像是活动结束了

**Comment by inoyna11** [comment]
> 报告，618抽盲盒的美丽研究院报错，好像是活动结束了

盲盒活动删了，研究院脚本不能用，待修复

**Comment by rececece** [comment]
> > 报告，618抽盲盒的美丽研究院报错，好像是活动结束了
> 
> 盲盒活动创作了，研究院脚本不能用，待修复

哇，大佬还回复我了，感谢！
