### ISSUE TITLE
口袋书店还是不行啊

### ISSUE THREAD

**Issue by 13071558875** [inoyna11/jd28#91]
口袋书店还是没有运行，看build直接就是error什么都没有

**Comment by inoyna11** [comment]
> 口袋书店还是没有运行，看build直接就是error什么都没有

每天必须手动进入活动才能使用脚本

**Comment by zhangleqin** [comment]
> > 口袋书店还是没有运行，看build直接就是error什么都没有
> 
> 每天必须手动进入活动才能使用脚本

看不到入口啊 京东图书能进 口袋书店找不到啊
