### ISSUE TITLE
宠汪汪(换20豆）运行时报WARNING

### ISSUE THREAD

**Issue by JackHuang90** [inoyna11/jd28#92]
运行之后一直报警告，且一直在运行，未停止。可能是运行定时器原因。

`WARNING:root:2021-06-01 16:07:18.513463未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:07:21.558054未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:07:24.591847未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:07:27.626468未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:07:30.659549未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:07:33.693319未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:07:36.727486未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:07:39.762861未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:07:42.797778未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:07:45.832349未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:07:48.866835未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:07:51.900432未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:07:54.932632未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:07:57.965064未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:08:00.998139未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:08:04.030498未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:08:07.064223未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:08:10.096878未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:08:13.130676未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:08:16.162502未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:08:19.197811未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:08:22.232059未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:08:25.265179未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:08:28.299014未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:08:31.332448未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:08:34.366074未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:08:37.401609未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:08:40.436360未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:08:43.470234未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:08:46.506526未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:08:49.541078未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:08:52.575396未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:08:55.610407未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:08:58.644766未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:09:01.682177未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:09:04.715862未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:09:07.750420未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:09:10.785006未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:09:13.818836未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:09:16.854838未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:09:19.890282未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:09:22.922576未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:09:25.956281未到2021-06-01 16:59:59.850000点`

**Comment by JackHuang90** [comment]
Run python3 accwait.py 0.1 0.1 59
accwait.py:37: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
  logging.warn(f'{datetime.datetime.now()}未到{target_time}点')
WARNING:root:2021-06-01 16:05:56.570708未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:05:59.605832未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:06:02.640950未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:06:05.675803未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:06:08.710750未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:06:11.746392未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:06:14.780629未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:06:17.815174未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:06:20.850157未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:06:23.884073未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:06:26.917359未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:06:29.950330未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:06:32.983648未到2021-06-01 16:59:59.850000点
WARNING:root:2021-06-01 16:06:36.017876未到2021-06-01 16:59:59.850000点

**Comment by inoyna11** [comment]
> Run python3 accwait.py 0.1 0.1 59
> accwait.py:37: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
> logging.warn(f'{datetime.datetime.now()}未到{target_time}点')
> WARNING:root:2021-06-01 16:05:56.570708未到2021-06-01 16:59:59.850000点
> WARNING:root:2021-06-01 16:05:59.605832未到2021-06-01 16:59:59.850000点
> WARNING:root:2021-06-01 16:06:02.640950未到2021-06-01 16:59:59.850000点
> WARNING:root:2021-06-01 16:06:05.675803未到2021-06-01 16:59:59.850000点
> WARNING:root:2021-06-01 16:06:08.710750未到2021-06-01 16:59:59.850000点
> WARNING:root:2021-06-01 16:06:11.746392未到2021-06-01 16:59:59.850000点
> WARNING:root:2021-06-01 16:06:14.780629未到2021-06-01 16:59:59.850000点
> WARNING:root:2021-06-01 16:06:17.815174未到2021-06-01 16:59:59.850000点
> WARNING:root:2021-06-01 16:06:20.850157未到2021-06-01 16:59:59.850000点
> WARNING:root:2021-06-01 16:06:23.884073未到2021-06-01 16:59:59.850000点
> WARNING:root:2021-06-01 16:06:26.917359未到2021-06-01 16:59:59.850000点
> WARNING:root:2021-06-01 16:06:29.950330未到2021-06-01 16:59:59.850000点
> WARNING:root:2021-06-01 16:06:32.983648未到2021-06-01 16:59:59.850000点
> WARNING:root:2021-06-01 16:06:36.017876未到2021-06-01 16:59:59.850000点

因为这个脚本需要0点才能抢到京豆，所以加的定时器
