### ISSUE TITLE
点点券checkout报错

### ISSUE THREAD

**Issue by KissCode** [inoyna11/jd28#93]
Run actions/checkout@v2
Syncing repository: hajiuhajiu/jdsign1112
Getting Git version info
Deleting the contents of '/home/runner/work/jd_script/jd_script'
Initializing the repository
Disabling automatic garbage collection
Setting up auth
Determining the default branch

**Comment by inoyna11** [comment]
> Run actions/checkout@v2
> Syncing repository: hajiuhajiu/jdsign1112
> Getting Git version info
> Deleting the contents of '/home/runner/work/jd_script/jd_script'
> Initializing the repository
> Disabling automatic garbage collection
> Setting up auth
> Determining the default branch

可以了

**Comment by KissCode** [comment]
我这边还是不行呢
Run actions/checkout@v2
  with:
    repository: hajiuhajiu/jdsign1112
    token: ***
    ssh-strict: true
    persist-credentials: true
    clean: true
    fetch-depth: 1
    lfs: false
    submodules: false
Syncing repository: hajiuhajiu/jdsign1112
Getting Git version info
  Working directory is '/home/runner/work/jd_script/jd_script'
  /usr/bin/git version
  git version 2.31.1
Deleting the contents of '/home/runner/work/jd_script/jd_script'
Initializing the repository
  /usr/bin/git init /home/runner/work/jd_script/jd_script
  hint: Using 'master' as the name for the initial branch. This default branch name
  hint: is subject to change. To configure the initial branch name to use in all
  hint: of your new repositories, which will suppress this warning, call:
  hint: 
  hint: 	git config --global init.defaultBranch <name>
  hint: 
  hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
  hint: 'development'. The just-created branch can be renamed via this command:
  hint: 
  hint: 	git branch -m <name>
  Initialized empty Git repository in /home/runner/work/jd_script/jd_script/.git/
  /usr/bin/git remote add origin https://github.com/hajiuhajiu/jdsign1112
Disabling automatic garbage collection
  /usr/bin/git config --local gc.auto 0
Setting up auth
  /usr/bin/git config --local --name-only --get-regexp core\.sshCommand
  /usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
  /usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
  /usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
  /usr/bin/git config --local http.https://github.com/.extraheader AUTHORIZATION: basic ***
Determining the default branch
  Retrieving the default branch name
  Not Found
  Waiting 20 seconds before trying again
  Retrieving the default branch name
  Not Found
  Waiting 19 seconds before trying again
  Retrieving the default branch name
  Error: Not Found

**Comment by KissCode** [comment]
直播抽奖 全局 报错
Run actions/checkout@v2
  with:
    repository: hajiuhajiu/jdsign1112
    ref: master
    token: ***
    ssh-strict: true
    persist-credentials: true
    clean: true
    fetch-depth: 1
    lfs: false
    submodules: false
Syncing repository: hajiuhajiu/jdsign1112
Getting Git version info
  Working directory is '/home/runner/work/jd_script/jd_script'
  /usr/bin/git version
  git version 2.31.1
Deleting the contents of '/home/runner/work/jd_script/jd_script'
Initializing the repository
  /usr/bin/git init /home/runner/work/jd_script/jd_script
  hint: Using 'master' as the name for the initial branch. This default branch name
  hint: is subject to change. To configure the initial branch name to use in all
  hint: of your new repositories, which will suppress this warning, call:
  hint: 
  hint: 	git config --global init.defaultBranch <name>
  hint: 
  hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
  hint: 'development'. The just-created branch can be renamed via this command:
  hint: 
  hint: 	git branch -m <name>
  Initialized empty Git repository in /home/runner/work/jd_script/jd_script/.git/
  /usr/bin/git remote add origin https://github.com/hajiuhajiu/jdsign1112
Disabling automatic garbage collection
  /usr/bin/git config --local gc.auto 0
Setting up auth
  /usr/bin/git config --local --name-only --get-regexp core\.sshCommand
  /usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
  /usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
  /usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
  /usr/bin/git config --local http.https://github.com/.extraheader AUTHORIZATION: basic ***
Fetching the repository
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/master*:refs/remotes/origin/master* +refs/tags/master*:refs/tags/master*
  remote: Repository not found.
  Error: fatal: repository 'https://github.com/hajiuhajiu/jdsign1112/' not found
  The process '/usr/bin/git' failed with exit code 128
  Waiting 10 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/master*:refs/remotes/origin/master* +refs/tags/master*:refs/tags/master*
  remote: Repository not found.
  Error: fatal: repository 'https://github.com/hajiuhajiu/jdsign1112/' not found
  The process '/usr/bin/git' failed with exit code 128
  Waiting 16 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/master*:refs/remotes/origin/master* +refs/tags/master*:refs/tags/master*
  remote: Repository not found.
  Error: fatal: repository 'https://github.com/hajiuhajiu/jdsign1112/' not found
  Error: The process '/usr/bin/git' failed with exit code 128

**Comment by KissCode** [comment]
粉丝互动 也是checked报错
Run actions/checkout@v2
Syncing repository: hajiuhajiu/jdsign1112
Getting Git version info
Deleting the contents of '/home/runner/work/jd_script/jd_script'
Initializing the repository
Disabling automatic garbage collection
Setting up auth
Fetching the repository
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/master*:refs/remotes/origin/master* +refs/tags/master*:refs/tags/master*
  remote: Repository not found.
  Error: fatal: repository 'https://github.com/hajiuhajiu/jdsign1112/' not found
  The process '/usr/bin/git' failed with exit code 128
  Waiting 15 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/master*:refs/remotes/origin/master* +refs/tags/master*:refs/tags/master*
  remote: Repository not found.
  Error: fatal: repository 'https://github.com/hajiuhajiu/jdsign1112/' not found
  The process '/usr/bin/git' failed with exit code 128
  Waiting 10 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/master*:refs/remotes/origin/master* +refs/tags/master*:refs/tags/master*
  remote: Repository not found.
  Error: fatal: repository 'https://github.com/hajiuhajiu/jdsign1112/' not found
  Error: The process '/usr/bin/git' failed with exit code 128

**Comment by inoyna11** [comment]
> Run actions/checkout@v2
> Syncing repository: hajiuhajiu/jdsign1112
> Getting Git version info
> Deleting the contents of '/home/runner/work/jd_script/jd_script'
> Initializing the repository
> Disabling automatic garbage collection
> Setting up auth
> Determining the default branch

同步我的脚本，然后重新运行

**Comment by inoyna11** [comment]
> 粉丝互动 也是checked报错
> Run actions/checkout@v2
> Syncing repository: hajiuhajiu/jdsign1112
> Getting Git version info
> Deleting the contents of '/home/runner/work/jd_script/jd_script'
> Initializing the repository
> Disabling automatic garbage collection
> Setting up auth
> Fetching the repository
> /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/master*:refs/remotes/origin/master* +refs/tags/master*:refs/tags/master*
> remote: Repository not found.
> Error: fatal: repository 'https://github.com/hajiuhajiu/jdsign1112/' not found
> The process '/usr/bin/git' failed with exit code 128
> Waiting 15 seconds before trying again
> /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/master*:refs/remotes/origin/master* +refs/tags/master*:refs/tags/master*
> remote: Repository not found.
> Error: fatal: repository 'https://github.com/hajiuhajiu/jdsign1112/' not found
> The process '/usr/bin/git' failed with exit code 128
> Waiting 10 seconds before trying again
> /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/master*:refs/remotes/origin/master* +refs/tags/master*:refs/tags/master*
> remote: Repository not found.
> Error: fatal: repository 'https://github.com/hajiuhajiu/jdsign1112/' not found
> Error: The process '/usr/bin/git' failed with exit code 128

已更新
