### ISSUE TITLE
怎么根据活动店铺ID找到店铺，店铺大转盘推送了中奖信息和活动店铺ID，怎么根据店铺ID找到店铺？谢谢大佬！

### ISSUE THREAD

**Issue by rececece** [inoyna11/jd28#95]
店铺大转盘推送了中奖信息和活动店铺ID，怎么根据店铺ID找到店铺？谢谢大佬！

**Comment by inoyna11** [comment]
> 店铺大转盘推送了中奖信息和活动店铺ID，怎么根据店铺ID找到店铺？谢谢大佬！

那个中奖是要在店铺消费很多钱才能送你奖品

**Comment by rececece** [comment]
> 你

谢谢大佬回复！也就是说，即便中奖了，也没啥用是吗？

**Comment by rececece** [comment]
> > 店铺大转盘推送了中奖信息和活动店铺ID，怎么根据店铺ID找到店铺？谢谢大佬！
> 
> 那个中奖是要在店铺消费很多钱才能送你奖品


谢谢大佬回复！也就是说，即便中奖了，也没啥用是吗？

**Comment by inoyna11** [comment]
> > > 店铺大转盘推送了中奖信息和活动店铺ID，怎么根据店铺ID找到店铺？谢谢大佬！
> > 
> > 
> > 那个中奖是要在店铺消费很多钱才能送你奖品
> 
> 谢谢大佬回复！也就是说，即便中奖了，也没啥用是吗？

是的，这个中奖几率很大，不过都是要在店铺消费才能送你
