### ISSUE TITLE
这个金融养猪是什么呀，直接报错了呀

### ISSUE THREAD

**Issue by xdeancc** [inoyna11/jd28#98]
![微信截图_20210602182837](https://user-images.githubusercontent.com/55089420/120464149-3339ba80-c3cf-11eb-9ea4-2fc668e3e801.png)

**Comment by inoyna11** [comment]
更新了   同步脚本在运行

**Comment by xdeancc** [comment]
> 更新了   同步脚本在运行

好的好的，我试试看，谢谢
