### ISSUE TITLE
萌宠收集金币报错

### ISSUE THREAD

**Issue by 13071558875** [inoyna11/jd28#99]
error，挺多脚本都error了，不知道怎么了

**Comment by 13071558875** [comment]
出现活动火爆了，[https://github.com/xoyi/jd_wbbny](url)，这个脚本解决了火爆的问题

**Comment by 13071558875** [comment]
直播间抽奖似乎要改一下了，那个作者貌似删掉了。出现了no found

**Comment by inoyna11** [comment]
> error，挺多脚本都error了，不知道怎么了

萌宠脚本应该是可以的，我刚试了
他的脚本只能自己抓包用，而且维持的时间应该很短
直播间抽奖好了
